use crate::{
    compile::DirectBindingKind,
    equality::{CoreExpr, QuantityId, SpecialRef, TimeReference},
    pipeline::PreparedExperiment,
    plan::{PlannedEquation, PlannedSlot},
};

pub fn emit_python_module(experiment: &PreparedExperiment) -> String {
    let model = &experiment.model;
    let bound = &experiment.bound;
    let plan = &experiment.plan;

    let mut lines = Vec::new();
    lines.push("# Generated by myco-core".to_string());
    lines.push(format!("MODEL_NAME = {:?}", model.syntax.name));
    lines.push(String::new());

    let quantity_names = model
        .equality
        .quantities
        .iter()
        .map(|quantity| quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!("QUANTITY_NAMES = {}", render_py_string_list(&quantity_names)));

    let state_names = bound
        .quantities
        .iter()
        .filter(|quantity| matches!(quantity.quantity.kind, crate::syntax::QuantityKind::State))
        .map(|quantity| quantity.quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!("STATE_NAMES = {}", render_py_string_list(&state_names)));

    let forcing_names = bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::DataSeries { .. }) => Some(quantity.quantity.name.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>();
    lines.push(format!("FORCING_NAMES = {}", render_py_string_list(&forcing_names)));

    let constant_names = bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::Constant) => Some(quantity.quantity.name.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>();
    lines.push(format!("CONSTANT_NAMES = {}", render_py_string_list(&constant_names)));
    lines.push(String::new());

    lines.push("OBSERVATION_SPECS = {".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!(
            "    {name}: {{\"loss\": {loss}, \"schedule\": {schedule}}},",
            name = py_string(&name),
            loss = py_string(match observation.loss {
                crate::compile::LossKind::Mse => "mse",
                crate::compile::LossKind::Huber => "huber",
            }),
            schedule = py_string(match &observation.schedule {
                crate::compile::ObservationSchedule::DensePerStep => "dense_per_step",
                crate::compile::ObservationSchedule::Sparse(_) => "sparse",
            })
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("SLOT_INTERFACES = {".to_string());
    for slot in &bound.slot_bindings {
        let input_names = slot
            .inputs
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        let output_names = slot
            .provides
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        lines.push(format!(
            "    {:?}: {{\"kind\": {:?}, \"inputs\": {}, \"outputs\": {}}},",
            slot.slot,
            slot.kind_name(),
            render_py_string_list(&input_names),
            render_py_string_list(&output_names)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PLAN_METADATA = {".to_string());
    lines.push(format!("    \"planned_slot_steps\": {},", plan.slot_steps.len()));
    lines.push(format!(
        "    \"planned_equation_steps\": {},",
        plan.equation_steps.len()
    ));
    lines.push(format!(
        "    \"planned_temporal_steps\": {},",
        plan.temporal_steps.len()
    ));
    lines.push(format!(
        "    \"alternative_path_count\": {},",
        plan.alternatives.len()
    ));
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("def init_params():".to_string());
    lines.push("    return {}".to_string());
    lines.push(String::new());

    lines.push("def _huber_loss(residual, delta=1.0):".to_string());
    lines.push("    abs_residual = abs(residual)".to_string());
    lines.push("    if abs_residual <= delta:".to_string());
    lines.push("        return 0.5 * residual * residual".to_string());
    lines.push("    return delta * (abs_residual - 0.5 * delta)".to_string());
    lines.push(String::new());

    lines.push("def step(state, forcing, constants, slot_providers, dt):".to_string());
    lines.push("    current = {}".to_string());
    lines.push("    current.update(constants)".to_string());
    lines.push("    current.update(forcing)".to_string());
    lines.push("    current.update(state)".to_string());
    lines.push(String::new());

    for slot in &plan.slot_steps {
        emit_slot_step(experiment, slot, &mut lines);
    }
    for equation in &plan.equation_steps {
        emit_equation_step(experiment, equation, &mut lines, "current");
    }

    lines.push("    next_state = dict(state)".to_string());
    for equation in &plan.temporal_steps {
        emit_equation_step(experiment, equation, &mut lines, "next_state");
    }
    lines.push("    return next_state, current".to_string());
    lines.push(String::new());

    lines.push("def rollout(initial_state, forcing_steps, constants, slot_providers, dt):".to_string());
    lines.push("    state = dict(initial_state)".to_string());
    lines.push("    trajectory = []".to_string());
    lines.push("    for forcing in forcing_steps:".to_string());
    lines.push("        state, current = step(state, forcing, constants, slot_providers, dt)".to_string());
    lines.push("        trajectory.append({\"current\": dict(current), \"state\": dict(state)})".to_string());
    lines.push("    return trajectory".to_string());
    lines.push(String::new());

    lines.push("def obs_loss(trajectory, observations):".to_string());
    lines.push("    total = 0.0".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!("    _obs = observations.get({})", py_string(&name)));
        lines.push("    if _obs is None:".to_string());
        lines.push("        raise KeyError('missing observation payload')".to_string());
        lines.push("    _values = _obs[\"values\"]".to_string());
        lines.push("    _mask = _obs[\"mask\"]".to_string());
        lines.push("    for step_index, frame in enumerate(trajectory):".to_string());
        lines.push("        if not _mask[step_index]:".to_string());
        lines.push("            continue".to_string());
        lines.push(format!(
            "        residual = frame[\"current\"][{name}] - _values[step_index]",
            name = py_string(&name)
        ));
        match observation.loss {
            crate::compile::LossKind::Mse => {
                lines.push("        total += residual * residual".to_string());
            }
            crate::compile::LossKind::Huber => {
                lines.push("        total += _huber_loss(residual)".to_string());
            }
        }
    }
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def consistency_loss(trajectory):".to_string());
    lines.push("    return 0.0".to_string());
    lines.push(String::new());

    lines.push("def soft_penalty_loss(trajectory):".to_string());
    lines.push("    return 0.0".to_string());
    lines.push(String::new());

    lines.push("def loss_components(trajectory, observations):".to_string());
    lines.push("    obs = obs_loss(trajectory, observations)".to_string());
    lines.push("    consistency = consistency_loss(trajectory)".to_string());
    lines.push("    soft_penalty = soft_penalty_loss(trajectory)".to_string());
    lines.push("    return {".to_string());
    lines.push("        \"obs_loss\": obs,".to_string());
    lines.push("        \"consistency_loss\": consistency,".to_string());
    lines.push("        \"soft_penalty_loss\": soft_penalty,".to_string());
    lines.push("        \"total_loss\": obs + consistency + soft_penalty,".to_string());
    lines.push("    }".to_string());
    lines.push(String::new());

    lines.push("def total_loss(trajectory, observations):".to_string());
    lines.push("    return loss_components(trajectory, observations)[\"total_loss\"]".to_string());
    lines.push(String::new());

    lines.join("\n")
}

fn emit_slot_step(experiment: &PreparedExperiment, slot: &PlannedSlot, lines: &mut Vec<String>) {
    let call = format!(
        "slot_providers[{name}]({args})",
        name = py_string(&slot.slot),
        args = slot
            .inputs
            .iter()
            .map(|quantity| format!("current[{name}]", name = py_string(&quantity_name(experiment, *quantity))))
            .collect::<Vec<_>>()
            .join(", ")
    );

    if slot.outputs.len() == 1 {
        lines.push(format!(
            "    current[{output}] = {call}",
            output = py_string(&quantity_name(experiment, slot.outputs[0]))
        ));
    } else {
        lines.push(format!("    _slot_out = {call}"));
        for (index, output) in slot.outputs.iter().enumerate() {
            lines.push(format!(
                "    current[{output}] = _slot_out[{index}]",
                output = py_string(&quantity_name(experiment, *output))
            ));
        }
    }
}

fn emit_equation_step(
    experiment: &PreparedExperiment,
    equation: &PlannedEquation,
    lines: &mut Vec<String>,
    target_map: &str,
) {
    let target = quantity_name(experiment, equation.output);
    let expr = render_expr(experiment, &equation.expression);
    lines.push(format!(
        "    {target_map}[{target}] = {expr}",
        target = py_string(&target)
    ));
}

fn render_expr(experiment: &PreparedExperiment, expr: &CoreExpr) -> String {
    match expr {
        CoreExpr::Quantity(reference) => match reference.time {
            TimeReference::Implicit | TimeReference::Relative(0) => format!(
                "current[{name}]",
                name = py_string(&quantity_name(experiment, reference.quantity))
            ),
            TimeReference::Relative(1) => format!(
                "next_state[{name}]",
                name = py_string(&quantity_name(experiment, reference.quantity))
            ),
            other => panic!("unsupported time reference in emitter: {other:?}"),
        },
        CoreExpr::Special(SpecialRef::Dt) => "dt".to_string(),
        CoreExpr::Number(number) => number.clone(),
        CoreExpr::Binary { op, left, right } => {
            let op_str = match op {
                crate::semantic::BinaryOp::Add => "+",
                crate::semantic::BinaryOp::Sub => "-",
                crate::semantic::BinaryOp::Mul => "*",
                crate::semantic::BinaryOp::Div => "/",
            };
            format!(
                "({left} {op_str} {right})",
                left = render_expr(experiment, left),
                right = render_expr(experiment, right)
            )
        }
    }
}

fn quantity_name(experiment: &PreparedExperiment, quantity: QuantityId) -> String {
    experiment.model.equality.quantities[quantity.0].name.clone()
}

fn render_py_string_list(values: &[impl AsRef<str>]) -> String {
    let items = values
        .iter()
        .map(|value| py_string(value.as_ref()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{items}]")
}

fn py_string(value: &str) -> String {
    format!("{value:?}")
}

trait SlotKindName {
    fn kind_name(&self) -> &'static str;
}

impl SlotKindName for crate::compile::ResolvedSlotBinding {
    fn kind_name(&self) -> &'static str {
        match self.kind {
            crate::compile::SlotBindingKind::DataSeries => "data_series",
            crate::compile::SlotBindingKind::Constant => "constant",
            crate::compile::SlotBindingKind::Learned => "learned",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        compile::{
            CompileMode, CompileSpec, DirectBindingKind, DirectBindingSpec, InitialStateSource,
            LossKind, ObservationSpec, ObservationSchedule, SlotBindingKind, SlotBindingSpec,
        },
        pipeline::{load_model, prepare_experiment},
    };

    const TINY_TREE: &str = include_str!("../tests/fixtures/tiny_tree.myco");

    #[test]
    fn emits_python_module_for_tiny_tree() {
        let model = load_model(TINY_TREE).expect("model should load");
        let experiment = prepare_experiment(&model, &tiny_tree_spec()).expect("experiment should prepare");
        let module = emit_python_module(&experiment);

        assert!(module.contains("MODEL_NAME = \"TinyTree\""));
        assert!(module.contains("OBSERVATION_SPECS = {"));
        assert!(module.contains("def step(state, forcing, constants, slot_providers, dt):"));
        assert!(module.contains("def rollout(initial_state, forcing_steps, constants, slot_providers, dt):"));
        assert!(module.contains("def obs_loss(trajectory, observations):"));
        assert!(module.contains("def total_loss(trajectory, observations):"));
        assert!(module.contains("current[\"stomata\"] = slot_providers[\"controller\"]("));
        assert!(module.contains("current[\"transpiration\"] = (current[\"stomata\"] * current[\"vpd_scale\"])"));
        assert!(module.contains("next_state[\"water\"] = (current[\"water\"] - (dt * current[\"transpiration\"]))"));
    }

    #[test]
    fn emits_inverted_equation_when_plan_uses_recovery_path() {
        let source = r#"
model Recover

external vpd_scale : scalar
state water : scalar
node stomata : scalar
node transpiration : scalar

relation demand_transpiration:
  transpiration = stomata * vpd_scale

temporal water_step:
  water[t+1] = water[t] - transpiration[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Fit,
                horizon_steps: 12,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "vpd_scale".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "transpiration".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let module = emit_python_module(&experiment);
        assert!(module.contains("current[\"stomata\"] = (current[\"transpiration\"] / current[\"vpd_scale\"])"));
    }

    fn tiny_tree_spec() -> CompileSpec {
        CompileSpec {
            mode: CompileMode::Train,
            horizon_steps: 24,
            direct_bindings: vec![
                DirectBindingSpec {
                    quantity: "vpd_scale".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "soil_water".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "hydraulic_cond".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "g_max".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "water".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
                DirectBindingSpec {
                    quantity: "carbon".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
            ],
            slot_bindings: vec![SlotBindingSpec {
                slot: "controller".to_string(),
                kind: SlotBindingKind::Learned,
            }],
            observations: vec![ObservationSpec {
                quantity: "transpiration".to_string(),
                loss: LossKind::Mse,
                schedule: ObservationSchedule::DensePerStep,
            }],
        }
    }
}
