use crate::{
    compile::DirectBindingKind,
    constraints::{ConstraintBound, PenaltySpec},
    equality::{CoreExpr, QuantityId, SpecialRef, TimeReference},
    pipeline::PreparedExperiment,
    plan::{AlternativePayload, PlannedEquation, PlannedSlot},
};

pub fn emit_python_module(experiment: &PreparedExperiment) -> String {
    let model = &experiment.model;
    let bound = &experiment.bound;
    let plan = &experiment.plan;

    let mut lines = Vec::new();
    lines.push("# Generated by myco-core".to_string());
    lines.push(format!("MODEL_NAME = {:?}", model.syntax.name));
    lines.push(format!(
        "COMPILE_MODE = {:?}",
        compile_mode_name(bound.mode)
    ));
    lines.push(String::new());

    let quantity_names = model
        .equality
        .quantities
        .iter()
        .map(|quantity| quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "QUANTITY_NAMES = {}",
        render_py_string_list(&quantity_names)
    ));

    let state_names = bound
        .quantities
        .iter()
        .filter(|quantity| matches!(quantity.quantity.kind, crate::syntax::QuantityKind::State))
        .map(|quantity| quantity.quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "STATE_NAMES = {}",
        render_py_string_list(&state_names)
    ));

    let forcing_names = bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::DataSeries { .. }) => Some(quantity.quantity.name.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>();
    lines.push(format!(
        "FORCING_NAMES = {}",
        render_py_string_list(&forcing_names)
    ));

    let constant_names = bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::Constant) => Some(quantity.quantity.name.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>();
    lines.push(format!(
        "CONSTANT_NAMES = {}",
        render_py_string_list(&constant_names)
    ));
    lines.push(String::new());

    lines.push("PROJECTION_METADATA = {".to_string());
    for slot in &bound.slot_bindings {
        if !matches!(slot.kind, crate::compile::SlotBindingKind::Learned) {
            continue;
        }
        for provided in &slot.provides {
            if let Some(projection) = projection_metadata(experiment, *provided) {
                lines.push(format!(
                    "    {name}: {projection},",
                    name = py_string(&quantity_name(experiment, *provided))
                ));
            }
        }
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PENALTY_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        let penalties = &quantity.constraint_set.penalties;
        if penalties.is_empty() {
            continue;
        }
        lines.push(format!(
            "    {name}: {penalties},",
            name = py_string(&quantity.name),
            penalties = render_python_penalties(penalties)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("OBSERVATION_SPECS = {".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!(
            "    {name}: {{\"loss\": {loss}, \"schedule\": {schedule}}},",
            name = py_string(&name),
            loss = py_string(match observation.loss {
                crate::compile::LossKind::Mse => "mse",
                crate::compile::LossKind::Huber => "huber",
            }),
            schedule = py_string(match &observation.schedule {
                crate::compile::ObservationSchedule::DensePerStep => "dense_per_step",
                crate::compile::ObservationSchedule::Sparse(_) => "sparse",
            })
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("SLOT_INTERFACES = {".to_string());
    for slot in &bound.slot_bindings {
        let input_names = slot
            .inputs
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        let output_names = slot
            .provides
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        lines.push(format!(
            "    {:?}: {{\"kind\": {:?}, \"inputs\": {}, \"outputs\": {}}},",
            slot.slot,
            slot.kind_name(),
            render_py_string_list(&input_names),
            render_py_string_list(&output_names)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PLAN_METADATA = {".to_string());
    lines.push(format!(
        "    \"planned_slot_steps\": {},",
        plan.slot_steps.len()
    ));
    lines.push(format!(
        "    \"planned_equation_steps\": {},",
        plan.equation_steps.len()
    ));
    lines.push(format!(
        "    \"planned_temporal_steps\": {},",
        plan.temporal_steps.len()
    ));
    lines.push(format!(
        "    \"alternative_path_count\": {},",
        plan.alternatives.len()
    ));
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("def init_params():".to_string());
    lines.push("    return {}".to_string());
    lines.push(String::new());

    lines.push("def _huber_loss(residual, delta=1.0):".to_string());
    lines.push("    abs_residual = abs(residual)".to_string());
    lines.push("    if abs_residual <= delta:".to_string());
    lines.push("        return 0.5 * residual * residual".to_string());
    lines.push("    return delta * (abs_residual - 0.5 * delta)".to_string());
    lines.push(String::new());

    lines.push("def _resolve_bound(bound, current):".to_string());
    lines.push("    if isinstance(bound, str):".to_string());
    lines.push("        return current[bound]".to_string());
    lines.push("    return bound".to_string());
    lines.push(String::new());

    lines.push("def _project_output(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return value".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        value = max(value, _resolve_bound(lower, current))".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        value = min(value, _resolve_bound(upper, current))".to_string());
    lines.push("    return value".to_string());
    lines.push(String::new());

    lines.push("def step(state, forcing, constants, slot_providers, dt):".to_string());
    lines.push("    current = {}".to_string());
    lines.push("    current[\"_alternatives\"] = {}".to_string());
    lines.push("    current.update(constants)".to_string());
    lines.push("    current.update(forcing)".to_string());
    lines.push("    current.update(state)".to_string());
    lines.push(String::new());

    for slot in &plan.slot_steps {
        emit_slot_step(experiment, slot, &mut lines);
    }
    for equation in &plan.equation_steps {
        emit_equation_step(experiment, equation, &mut lines, "current");
    }
    for alternative in &plan.alternatives {
        emit_alternative_step(experiment, alternative, &mut lines);
    }

    lines.push("    next_state = dict(state)".to_string());
    for equation in &plan.temporal_steps {
        emit_equation_step(experiment, equation, &mut lines, "next_state");
    }
    lines.push("    return next_state, current".to_string());
    lines.push(String::new());

    lines.push(
        "def rollout(initial_state, forcing_steps, constants, slot_providers, dt):".to_string(),
    );
    lines.push("    state = dict(initial_state)".to_string());
    lines.push("    trajectory = []".to_string());
    lines.push("    for forcing in forcing_steps:".to_string());
    lines.push(
        "        state, current = step(state, forcing, constants, slot_providers, dt)".to_string(),
    );
    lines.push(
        "        trajectory.append({\"current\": dict(current), \"state\": dict(state)})"
            .to_string(),
    );
    lines.push("    return trajectory".to_string());
    lines.push(String::new());

    lines.push("def obs_loss(trajectory, observations):".to_string());
    lines.push("    total = 0.0".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!("    _obs = observations.get({})", py_string(&name)));
        lines.push("    if _obs is None:".to_string());
        lines.push("        raise KeyError('missing observation payload')".to_string());
        lines.push("    _values = _obs[\"values\"]".to_string());
        lines.push("    _mask = _obs[\"mask\"]".to_string());
        lines.push("    for step_index, frame in enumerate(trajectory):".to_string());
        lines.push("        if not _mask[step_index]:".to_string());
        lines.push("            continue".to_string());
        lines.push(format!(
            "        residual = frame[\"current\"][{name}] - _values[step_index]",
            name = py_string(&name)
        ));
        match observation.loss {
            crate::compile::LossKind::Mse => {
                lines.push("        total += residual * residual".to_string());
            }
            crate::compile::LossKind::Huber => {
                lines.push("        total += _huber_loss(residual)".to_string());
            }
        }
    }
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def consistency_loss(trajectory):".to_string());
    lines.push("    total = 0.0".to_string());
    lines.push("    for frame in trajectory:".to_string());
    lines.push("        alternatives = frame[\"current\"].get(\"_alternatives\", {})".to_string());
    lines.push("        for output_name, entries in alternatives.items():".to_string());
    lines.push("            canonical = frame[\"current\"][output_name]".to_string());
    lines.push("            for entry in entries:".to_string());
    lines.push("                residual = canonical - entry[\"value\"]".to_string());
    lines.push("                total += residual * residual".to_string());
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def soft_penalty_loss(trajectory):".to_string());
    lines.push("    total = 0.0".to_string());
    lines.push("    for name, penalties in PENALTY_METADATA.items():".to_string());
    lines.push("        for penalty in penalties:".to_string());
    lines.push("            if penalty[\"kind\"] == \"smooth\":".to_string());
    lines.push(
        "                values = [frame[\"current\"][name] for frame in trajectory]".to_string(),
    );
    lines.push("                for prev, curr in zip(values, values[1:]):".to_string());
    lines.push("                    delta = curr - prev".to_string());
    lines.push("                    total += penalty[\"weight\"] * delta * delta".to_string());
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def loss_components(trajectory, observations):".to_string());
    lines.push("    obs = obs_loss(trajectory, observations)".to_string());
    lines.push("    consistency = consistency_loss(trajectory)".to_string());
    lines.push("    soft_penalty = soft_penalty_loss(trajectory)".to_string());
    lines.push("    return {".to_string());
    lines.push("        \"obs_loss\": obs,".to_string());
    lines.push("        \"consistency_loss\": consistency,".to_string());
    lines.push("        \"soft_penalty_loss\": soft_penalty,".to_string());
    lines.push("        \"total_loss\": obs + consistency + soft_penalty,".to_string());
    lines.push("    }".to_string());
    lines.push(String::new());

    lines.push("def total_loss(trajectory, observations):".to_string());
    lines.push("    return loss_components(trajectory, observations)[\"total_loss\"]".to_string());
    lines.push(String::new());

    lines.join("\n")
}

pub fn emit_jax_module(experiment: &PreparedExperiment) -> String {
    let model = &experiment.model;
    let bound = &experiment.bound;
    let plan = &experiment.plan;

    let mut lines = Vec::new();
    lines.push("# Generated by myco-core".to_string());
    lines.push("import jax.numpy as jnp".to_string());
    lines.push("import jax.nn as jnn".to_string());
    lines.push("from jax import lax".to_string());
    lines.push(String::new());
    lines.push(format!("MODEL_NAME = {:?}", model.syntax.name));
    lines.push(format!(
        "COMPILE_MODE = {:?}",
        compile_mode_name(bound.mode)
    ));
    lines.push(String::new());

    let quantity_names = model
        .equality
        .quantities
        .iter()
        .map(|quantity| quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "QUANTITY_NAMES = {}",
        render_py_string_list(&quantity_names)
    ));

    let state_names = bound
        .quantities
        .iter()
        .filter(|quantity| matches!(quantity.quantity.kind, crate::syntax::QuantityKind::State))
        .map(|quantity| quantity.quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "STATE_NAMES = {}",
        render_py_string_list(&state_names)
    ));

    let forcing_names = bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::DataSeries { .. }) => Some(quantity.quantity.name.as_str()),
            _ => None,
        })
        .collect::<Vec<_>>();
    lines.push(format!(
        "FORCING_NAMES = {}",
        render_py_string_list(&forcing_names)
    ));
    lines.push(String::new());

    lines.push("PROJECTION_METADATA = {".to_string());
    for slot in &bound.slot_bindings {
        if !matches!(slot.kind, crate::compile::SlotBindingKind::Learned) {
            continue;
        }
        for provided in &slot.provides {
            if let Some(projection) = projection_metadata(experiment, *provided) {
                lines.push(format!(
                    "    {name}: {projection},",
                    name = py_string(&quantity_name(experiment, *provided))
                ));
            }
        }
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PENALTY_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        let penalties = &quantity.constraint_set.penalties;
        if penalties.is_empty() {
            continue;
        }
        lines.push(format!(
            "    {name}: {penalties},",
            name = py_string(&quantity.name),
            penalties = render_python_penalties(penalties)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("OBSERVATION_SPECS = {".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!(
            "    {name}: {{\"loss\": {loss}, \"schedule\": {schedule}}},",
            name = py_string(&name),
            loss = py_string(match observation.loss {
                crate::compile::LossKind::Mse => "mse",
                crate::compile::LossKind::Huber => "huber",
            }),
            schedule = py_string(match &observation.schedule {
                crate::compile::ObservationSchedule::DensePerStep => "dense_per_step",
                crate::compile::ObservationSchedule::Sparse(_) => "sparse",
            })
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PLAN_METADATA = {".to_string());
    lines.push(format!(
        "    \"planned_slot_steps\": {},",
        plan.slot_steps.len()
    ));
    lines.push(format!(
        "    \"planned_equation_steps\": {},",
        plan.equation_steps.len()
    ));
    lines.push(format!(
        "    \"planned_temporal_steps\": {},",
        plan.temporal_steps.len()
    ));
    lines.push(format!(
        "    \"alternative_path_count\": {},",
        plan.alternatives.len()
    ));
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("def init_params():".to_string());
    lines.push("    return {}".to_string());
    lines.push(String::new());

    lines.push("def _resolve_bound(bound, current):".to_string());
    lines.push("    if isinstance(bound, str):".to_string());
    lines.push("        return current[bound]".to_string());
    lines.push("    return jnp.asarray(bound)".to_string());
    lines.push(String::new());

    lines.push("def _project_output(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return value".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if lower is not None and upper is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        span = upper_v - lower_v".to_string());
    lines.push("        return lower_v + span * jnn.sigmoid(value)".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        return lower_v + jnn.softplus(value - lower_v)".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        return upper_v - jnn.softplus(upper_v - value)".to_string());
    lines.push("    return value".to_string());
    lines.push(String::new());

    lines.push("def _huber_loss(residual, delta=1.0):".to_string());
    lines.push("    abs_residual = jnp.abs(residual)".to_string());
    lines.push("    return jnp.where(abs_residual <= delta, 0.5 * residual * residual, delta * (abs_residual - 0.5 * delta))".to_string());
    lines.push(String::new());

    lines.push("def step(state, forcing, constants, slot_providers, dt):".to_string());
    lines.push("    current = {**constants, **forcing, **state}".to_string());
    for slot in &plan.slot_steps {
        emit_slot_step(experiment, slot, &mut lines);
    }
    for equation in &plan.equation_steps {
        emit_equation_step(experiment, equation, &mut lines, "current");
    }
    lines.push("    next_state = dict(state)".to_string());
    for equation in &plan.temporal_steps {
        emit_equation_step(experiment, equation, &mut lines, "next_state");
    }
    lines.push("    return next_state, current".to_string());
    lines.push(String::new());

    lines.push(
        "def rollout(initial_state, forcing_series, constants, slot_providers, dt):".to_string(),
    );
    lines.push("    def _scan_step(state, forcing_t):".to_string());
    lines.push(
        "        next_state, current = step(state, forcing_t, constants, slot_providers, dt)"
            .to_string(),
    );
    lines.push("        return next_state, current".to_string());
    lines.push("    return lax.scan(_scan_step, initial_state, forcing_series)".to_string());
    lines.push(String::new());

    lines.push("def obs_loss(history, observations):".to_string());
    lines.push("    total = 0.0".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!("    _obs = observations.get({})", py_string(&name)));
        lines.push("    if _obs is None:".to_string());
        lines.push("        raise KeyError('missing observation payload')".to_string());
        lines.push("    _values = jnp.asarray(_obs[\"values\"])".to_string());
        lines.push("    _mask = jnp.asarray(_obs[\"mask\"])".to_string());
        lines.push(format!(
            "    _residual = history[{name}] - _values",
            name = py_string(&name)
        ));
        match observation.loss {
            crate::compile::LossKind::Mse => {
                lines.push(
                    "    total += jnp.sum(jnp.where(_mask, _residual * _residual, 0.0))"
                        .to_string(),
                );
            }
            crate::compile::LossKind::Huber => {
                lines.push(
                    "    total += jnp.sum(jnp.where(_mask, _huber_loss(_residual), 0.0))"
                        .to_string(),
                );
            }
        }
    }
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def consistency_loss(history, constants, slot_providers):".to_string());
    lines.push("    total = 0.0".to_string());
    for alternative in &plan.alternatives {
        if let AlternativePayload::Equation { expression } = &alternative.payload {
            let output_name = quantity_name(experiment, alternative.output);
            let alt_expr =
                render_history_expr_for_output_unit(experiment, alternative.output, expression);
            lines.push(format!(
                "    _residual = history[{output}] - ({alt_expr})",
                output = py_string(&output_name)
            ));
            lines.push("    total += jnp.sum(_residual * _residual)".to_string());
        }
    }
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def soft_penalty_loss(history):".to_string());
    lines.push("    total = 0.0".to_string());
    lines.push("    for name, penalties in PENALTY_METADATA.items():".to_string());
    lines.push("        values = history[name]".to_string());
    lines.push("        for penalty in penalties:".to_string());
    lines.push("            if penalty[\"kind\"] == \"smooth\":".to_string());
    lines.push("                delta = values[1:] - values[:-1]".to_string());
    lines.push("                total += penalty[\"weight\"] * jnp.sum(delta * delta)".to_string());
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push(
        "def loss_components(history, observations, constants=None, slot_providers=None):"
            .to_string(),
    );
    lines.push("    constants = {} if constants is None else constants".to_string());
    lines.push("    slot_providers = {} if slot_providers is None else slot_providers".to_string());
    lines.push("    obs = obs_loss(history, observations)".to_string());
    lines
        .push("    consistency = consistency_loss(history, constants, slot_providers)".to_string());
    lines.push("    soft_penalty = soft_penalty_loss(history)".to_string());
    lines.push("    return {".to_string());
    lines.push("        \"obs_loss\": obs,".to_string());
    lines.push("        \"consistency_loss\": consistency,".to_string());
    lines.push("        \"soft_penalty_loss\": soft_penalty,".to_string());
    lines.push("        \"total_loss\": obs + consistency + soft_penalty,".to_string());
    lines.push("    }".to_string());
    lines.push(String::new());

    lines.push(
        "def total_loss(history, observations, constants=None, slot_providers=None):".to_string(),
    );
    lines.push("    return loss_components(history, observations, constants=constants, slot_providers=slot_providers)[\"total_loss\"]".to_string());
    lines.push(String::new());

    lines.join("\n")
}

fn emit_slot_step(experiment: &PreparedExperiment, slot: &PlannedSlot, lines: &mut Vec<String>) {
    let call = format!(
        "slot_providers[{name}]({args})",
        name = py_string(&slot.slot),
        args = slot
            .inputs
            .iter()
            .map(|quantity| format!(
                "current[{name}]",
                name = py_string(&quantity_name(experiment, *quantity))
            ))
            .collect::<Vec<_>>()
            .join(", ")
    );

    if slot.outputs.len() == 1 {
        lines.push(format!(
            "    current[{output}] = _project_output({output}, {call}, current)",
            output = py_string(&quantity_name(experiment, slot.outputs[0]))
        ));
    } else {
        lines.push(format!("    _slot_out = {call}"));
        for (index, output) in slot.outputs.iter().enumerate() {
            lines.push(format!(
                "    current[{output}] = _project_output({output}, _slot_out[{index}], current)",
                output = py_string(&quantity_name(experiment, *output))
            ));
        }
    }
}

fn emit_equation_step(
    experiment: &PreparedExperiment,
    equation: &PlannedEquation,
    lines: &mut Vec<String>,
    target_map: &str,
) {
    let target = quantity_name(experiment, equation.output);
    let expr = render_expr_for_output_unit(experiment, equation.output, &equation.expression);
    lines.push(format!(
        "    {target_map}[{target}] = {expr}",
        target = py_string(&target)
    ));
}

fn emit_alternative_step(
    experiment: &PreparedExperiment,
    alternative: &crate::plan::AlternativePath,
    lines: &mut Vec<String>,
) {
    let output_name = quantity_name(experiment, alternative.output);
    let value_expr = match &alternative.payload {
        AlternativePayload::Equation { expression } => {
            render_expr_for_output_unit(experiment, alternative.output, expression)
        }
        AlternativePayload::Slot { inputs } => {
            let slot_name = match &alternative.source {
                crate::plan::PlanSource::Slot(slot) => slot,
                crate::plan::PlanSource::Equation(_) => {
                    unreachable!("slot payload requires slot source")
                }
            };
            format!(
                "slot_providers[{name}]({args})",
                name = py_string(slot_name),
                args = inputs
                    .iter()
                    .map(|quantity| format!(
                        "current[{name}]",
                        name = py_string(&quantity_name(experiment, *quantity))
                    ))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
    };

    lines.push(format!(
        "    current[\"_alternatives\"].setdefault({output}, []).append({{\"source\": {source}, \"direction\": {direction}, \"value\": {value}}})",
        output = py_string(&output_name),
        source = py_string(&alternative_source_label(&alternative.source)),
        direction = py_string(match alternative.direction {
            crate::plan::CandidateDirection::Forward => "forward",
            crate::plan::CandidateDirection::Inverted => "inverted",
            crate::plan::CandidateDirection::Provider => "provider",
        }),
        value = value_expr
    ));
}

fn render_expr_base(experiment: &PreparedExperiment, expr: &CoreExpr) -> String {
    match expr {
        CoreExpr::Quantity(reference) => match reference.time {
            TimeReference::Implicit | TimeReference::Relative(0) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "current[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            TimeReference::Relative(1) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "next_state[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            other => panic!("unsupported time reference in emitter: {other:?}"),
        },
        CoreExpr::Special(SpecialRef::Dt) => "dt".to_string(),
        CoreExpr::Number(number) => number.clone(),
        CoreExpr::Binary { op, left, right } => {
            let op_str = match op {
                crate::semantic::BinaryOp::Add => "+",
                crate::semantic::BinaryOp::Sub => "-",
                crate::semantic::BinaryOp::Mul => "*",
                crate::semantic::BinaryOp::Div => "/",
            };
            format!(
                "({left} {op_str} {right})",
                left = render_expr_base(experiment, left),
                right = render_expr_base(experiment, right)
            )
        }
    }
}

fn render_expr_for_output_unit(
    experiment: &PreparedExperiment,
    output: QuantityId,
    expr: &CoreExpr,
) -> String {
    let expr_base = render_expr_base(experiment, expr);
    scale_from_base(experiment, output, expr_base)
}

fn render_history_expr_base(experiment: &PreparedExperiment, expr: &CoreExpr) -> String {
    match expr {
        CoreExpr::Quantity(reference) => match reference.time {
            TimeReference::Implicit | TimeReference::Relative(0) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "history[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            TimeReference::Relative(1) => {
                panic!("next-step references are not supported in JAX history expressions")
            }
            other => panic!("unsupported time reference in JAX history emitter: {other:?}"),
        },
        CoreExpr::Special(SpecialRef::Dt) => "1.0".to_string(),
        CoreExpr::Number(number) => number.clone(),
        CoreExpr::Binary { op, left, right } => {
            let op_str = match op {
                crate::semantic::BinaryOp::Add => "+",
                crate::semantic::BinaryOp::Sub => "-",
                crate::semantic::BinaryOp::Mul => "*",
                crate::semantic::BinaryOp::Div => "/",
            };
            format!(
                "({left} {op_str} {right})",
                left = render_history_expr_base(experiment, left),
                right = render_history_expr_base(experiment, right)
            )
        }
    }
}

fn render_history_expr_for_output_unit(
    experiment: &PreparedExperiment,
    output: QuantityId,
    expr: &CoreExpr,
) -> String {
    let expr_base = render_history_expr_base(experiment, expr);
    scale_from_base(experiment, output, expr_base)
}

fn quantity_name(experiment: &PreparedExperiment, quantity: QuantityId) -> String {
    experiment.model.equality.quantities[quantity.0]
        .name
        .clone()
}

fn scale_to_base(experiment: &PreparedExperiment, quantity: QuantityId) -> i64 {
    experiment.model.equality.quantities[quantity.0]
        .type_info
        .scale_to_base
}

fn render_quantity_read(
    experiment: &PreparedExperiment,
    quantity: QuantityId,
    expression: &str,
) -> String {
    let scale = scale_to_base(experiment, quantity);
    if scale == 1 {
        expression.to_string()
    } else {
        format!("({expression} * {})", render_scale(scale))
    }
}

fn scale_from_base(
    experiment: &PreparedExperiment,
    quantity: QuantityId,
    expression: String,
) -> String {
    let scale = scale_to_base(experiment, quantity);
    if scale == 1 {
        expression
    } else {
        format!("(({expression}) / {})", render_scale(scale))
    }
}

fn render_scale(scale: i64) -> String {
    format!("{scale:?}")
}

fn render_py_string_list(values: &[impl AsRef<str>]) -> String {
    let items = values
        .iter()
        .map(|value| py_string(value.as_ref()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{items}]")
}

fn py_string(value: &str) -> String {
    format!("{value:?}")
}

fn alternative_source_label(source: &crate::plan::PlanSource) -> String {
    match source {
        crate::plan::PlanSource::Slot(name) | crate::plan::PlanSource::Equation(name) => {
            name.clone()
        }
    }
}

fn compile_mode_name(mode: crate::compile::CompileMode) -> &'static str {
    match mode {
        crate::compile::CompileMode::Simulate => "simulate",
        crate::compile::CompileMode::Fit => "fit",
        crate::compile::CompileMode::Train => "train",
    }
}

fn projection_metadata(experiment: &PreparedExperiment, quantity: QuantityId) -> Option<String> {
    let constraint_set = &experiment.model.equality.quantities[quantity.0].constraint_set;
    let lower = constraint_set.lower.clone();
    let upper = constraint_set.upper.clone();

    if lower.is_none() && upper.is_none() {
        return None;
    }

    let mut fields = Vec::new();
    if let Some(bound) = lower {
        fields.push(format!("\"lower\": {}", render_projection_bound(&bound)));
    }
    if let Some(bound) = upper {
        fields.push(format!("\"upper\": {}", render_projection_bound(&bound)));
    }

    Some(format!("{{{}}}", fields.join(", ")))
}

fn render_projection_bound(bound: &ConstraintBound) -> String {
    match bound {
        ConstraintBound::Number(value) => value.clone(),
        ConstraintBound::Quantity(name) => py_string(name),
    }
}

fn render_python_penalties(penalties: &[PenaltySpec]) -> String {
    let rendered = penalties
        .iter()
        .map(|penalty| match penalty {
            PenaltySpec::Smooth { weight } => {
                format!("{{\"kind\": \"smooth\", \"weight\": {weight}}}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered}]")
}

trait SlotKindName {
    fn kind_name(&self) -> &'static str;
}

impl SlotKindName for crate::compile::ResolvedSlotBinding {
    fn kind_name(&self) -> &'static str {
        match self.kind {
            crate::compile::SlotBindingKind::DataSeries => "data_series",
            crate::compile::SlotBindingKind::Constant => "constant",
            crate::compile::SlotBindingKind::Learned => "learned",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        compile::{
            CompileMode, CompileSpec, DirectBindingKind, DirectBindingSpec, InitialStateSource,
            LossKind, ObservationSchedule, ObservationSpec, SlotBindingKind, SlotBindingSpec,
        },
        pipeline::{load_model, prepare_experiment},
    };

    const TINY_TREE: &str = include_str!("../tests/fixtures/tiny_tree.myco");

    #[test]
    fn emits_python_module_for_tiny_tree() {
        let model = load_model(TINY_TREE).expect("model should load");
        let experiment =
            prepare_experiment(&model, &tiny_tree_spec()).expect("experiment should prepare");
        let module = emit_python_module(&experiment);

        assert!(module.contains("MODEL_NAME = \"TinyTree\""));
        assert!(module.contains("COMPILE_MODE = \"train\""));
        assert!(module.contains("PROJECTION_METADATA = {"));
        assert!(module.contains("\"stomata\": {\"lower\": 0, \"upper\": \"g_max\"},"));
        assert!(module.contains("OBSERVATION_SPECS = {"));
        assert!(module.contains("def step(state, forcing, constants, slot_providers, dt):"));
        assert!(
            module.contains(
                "def rollout(initial_state, forcing_steps, constants, slot_providers, dt):"
            )
        );
        assert!(module.contains("def obs_loss(trajectory, observations):"));
        assert!(module.contains("def consistency_loss(trajectory):"));
        assert!(module.contains("def total_loss(trajectory, observations):"));
        assert!(module.contains(
            "current[\"stomata\"] = _project_output(\"stomata\", slot_providers[\"controller\"]("
        ));
        assert!(
            module.contains("current[\"_alternatives\"].setdefault(\"transpiration\", []).append(")
        );
        assert!(module.contains(
            "current[\"transpiration\"] = (current[\"stomata\"] * current[\"vpd_scale\"])"
        ));
        assert!(module.contains(
            "next_state[\"water\"] = (current[\"water\"] - (dt * current[\"transpiration\"]))"
        ));
    }

    #[test]
    fn emits_jax_module_for_tiny_tree() {
        let model = load_model(TINY_TREE).expect("model should load");
        let experiment =
            prepare_experiment(&model, &tiny_tree_spec()).expect("experiment should prepare");
        let module = emit_jax_module(&experiment);

        assert!(module.contains("import jax.numpy as jnp"));
        assert!(module.contains("import jax.nn as jnn"));
        assert!(module.contains("from jax import lax"));
        assert!(module.contains("COMPILE_MODE = \"train\""));
        assert!(module.contains("return lax.scan(_scan_step, initial_state, forcing_series)"));
        assert!(module.contains("jnp.where"));
        assert!(module.contains("jnn.sigmoid"));
        assert!(module.contains("jnn.softplus"));
        assert!(module.contains("def consistency_loss(history, constants, slot_providers):"));
        assert!(module.contains("history[\"transpiration\"] - ((history[\"hydraulic_cond\"] * (history[\"soil_water\"] - history[\"water\"])))"));
    }

    #[test]
    fn emits_soft_penalty_metadata_and_loss_code() {
        let source = r#"
model Penalized

external forcing : scalar
state water : scalar
node stomata : scalar {
  self >= 0
  self <= g_max
  penalty smooth(weight=0.25)
}
node g_max : scalar

slot controller provides [stomata]:
  inputs = [forcing, g_max]

temporal water_step:
  water[t+1] = water[t] + stomata[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Train,
                horizon_steps: 8,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "forcing".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..8).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "g_max".to_string(),
                        kind: DirectBindingKind::Constant,
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![SlotBindingSpec {
                    slot: "controller".to_string(),
                    kind: SlotBindingKind::Learned,
                }],
                observations: vec![ObservationSpec {
                    quantity: "stomata".to_string(),
                    loss: LossKind::Mse,
                    schedule: ObservationSchedule::DensePerStep,
                }],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("PENALTY_METADATA = {"));
        assert!(python_module.contains("\"stomata\": [{\"kind\": \"smooth\", \"weight\": 0.25}],"));
        assert!(python_module.contains("def soft_penalty_loss(trajectory):"));
        assert!(python_module.contains("total += penalty[\"weight\"] * delta * delta"));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("PENALTY_METADATA = {"));
        assert!(jax_module.contains("\"stomata\": [{\"kind\": \"smooth\", \"weight\": 0.25}],"));
        assert!(jax_module.contains("def soft_penalty_loss(history):"));
        assert!(jax_module.contains("delta = values[1:] - values[:-1]"));
        assert!(jax_module.contains("total += penalty[\"weight\"] * jnp.sum(delta * delta)"));
    }

    #[test]
    fn emits_jax_inverted_equation_when_plan_uses_recovery_path() {
        let source = r#"
model Recover

external vpd_scale : scalar
state water : scalar
node stomata : scalar
node transpiration : scalar

relation demand_transpiration:
  transpiration = stomata * vpd_scale

temporal water_step:
  water[t+1] = water[t] - transpiration[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 12,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "vpd_scale".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "transpiration".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let module = emit_jax_module(&experiment);
        assert!(module.contains(
            "current[\"stomata\"] = (current[\"transpiration\"] / current[\"vpd_scale\"])"
        ));
    }

    #[test]
    fn emits_unit_conversion_for_equation_outputs() {
        let source = r#"
model UnitConvert

node x : potential@MPa
node y : potential@kPa

relation assign:
  x = y
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 1,
                direct_bindings: vec![DirectBindingSpec {
                    quantity: "y".to_string(),
                    kind: DirectBindingKind::Constant,
                }],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("current[\"x\"] = "));
        assert!(python_module.contains("current[\"y\"] * 1000"));
        assert!(python_module.contains("/ 1000000"));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("current[\"x\"] = "));
        assert!(jax_module.contains("current[\"y\"] * 1000"));
        assert!(jax_module.contains("/ 1000000"));
    }

    #[test]
    fn emits_inverted_equation_when_plan_uses_recovery_path() {
        let source = r#"
model Recover

external vpd_scale : scalar
state water : scalar
node stomata : scalar
node transpiration : scalar

relation demand_transpiration:
  transpiration = stomata * vpd_scale

temporal water_step:
  water[t+1] = water[t] - transpiration[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 12,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "vpd_scale".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "transpiration".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let module = emit_python_module(&experiment);
        assert!(module.contains(
            "current[\"stomata\"] = (current[\"transpiration\"] / current[\"vpd_scale\"])"
        ));
    }

    fn tiny_tree_spec() -> CompileSpec {
        CompileSpec {
            mode: CompileMode::Train,
            horizon_steps: 24,
            direct_bindings: vec![
                DirectBindingSpec {
                    quantity: "vpd_scale".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "soil_water".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "hydraulic_cond".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "g_max".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "water".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
                DirectBindingSpec {
                    quantity: "carbon".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
            ],
            slot_bindings: vec![SlotBindingSpec {
                slot: "controller".to_string(),
                kind: SlotBindingKind::Learned,
            }],
            observations: vec![ObservationSpec {
                quantity: "transpiration".to_string(),
                loss: LossKind::Mse,
                schedule: ObservationSchedule::DensePerStep,
            }],
        }
    }
}
