use crate::{
    compile::{ConsistencyPolicy, DirectBindingKind, InitialStateSource, SlotBindingKind},
    constraints::{ConstraintBound, PenaltySpec},
    equality::{CoreExpr, QuantityId, SpecialRef, TimeReference},
    pipeline::PreparedExperiment,
    plan::{AlternativePayload, PlannedEquation, PlannedSlot},
};

pub fn emit_python_module(experiment: &PreparedExperiment) -> String {
    let model = &experiment.model;
    let bound = &experiment.bound;
    let plan = &experiment.plan;

    let mut lines = Vec::new();
    lines.push("# Generated by myco-core".to_string());
    lines.push(format!("MODEL_NAME = {:?}", model.syntax.name));
    lines.push(format!(
        "COMPILE_MODE = {:?}",
        compile_mode_name(bound.mode)
    ));
    lines.push(String::new());

    let quantity_names = model
        .equality
        .quantities
        .iter()
        .map(|quantity| quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "QUANTITY_NAMES = {}",
        render_py_string_list(&quantity_names)
    ));

    let persistent_quantity_names = persistent_quantity_names(bound, experiment);
    lines.push(format!(
        "PERSISTENT_QUANTITY_NAMES = {}",
        render_py_string_list(&persistent_quantity_names)
    ));

    let forcing_names = forcing_quantity_names(experiment);
    lines.push(format!(
        "FORCING_NAMES = {}",
        render_py_string_list(&forcing_names)
    ));

    let constant_names = constant_quantity_names(experiment);
    lines.push(format!(
        "CONSTANT_NAMES = {}",
        render_py_string_list(&constant_names)
    ));
    lines.push(format!("HORIZON_STEPS = {}", bound.horizon_steps));
    lines.push("SAFE_DIV_EPS = 1e-8".to_string());
    let learned_initial_state_names = learned_initial_state_names(bound, experiment);
    let required_initial_state_names = required_initial_state_names(bound, experiment);
    let learned_slot_names = learned_slot_names(bound);
    lines.push(format!(
        "LEARNED_INITIAL_STATE_NAMES = {}",
        render_py_string_list(&learned_initial_state_names)
    ));
    lines.push(format!(
        "REQUIRED_INITIAL_STATE_NAMES = {}",
        render_py_string_list(&required_initial_state_names)
    ));
    lines.push(format!(
        "LEARNED_SLOT_NAMES = {}",
        render_py_string_list(&learned_slot_names)
    ));
    lines.push(format!(
        "CONSISTENCY_POLICY = {:?}",
        consistency_policy_name(bound.consistency_policy)
    ));
    lines.push(format!(
        "CONSTRAINT_RUNTIME_POLICY = {:?}",
        python_constraint_runtime_policy_name()
    ));
    lines.push(format!(
        "LOSS_HELPERS_ENABLED = {}",
        if mode_emits_loss_helpers(bound.mode) {
            "True"
        } else {
            "False"
        }
    ));
    lines.push(String::new());

    lines.push("PROJECTION_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        if let Some(projection) = projection_metadata(experiment, quantity.id) {
            lines.push(format!(
                "    {name}: {projection},",
                name = py_string(&quantity.name)
            ));
        }
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push(format!(
        "TRAINABLE_METADATA = {{\"learned_initial_state\": {}, \"learned_slots\": {}}}",
        render_py_string_list(&learned_initial_state_names),
        render_py_string_list(&learned_slot_names)
    ));
    lines.push(String::new());

    lines.push("PENALTY_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        let penalties = &quantity.constraint_set.penalties;
        if penalties.is_empty() {
            continue;
        }
        lines.push(format!(
            "    {name}: {penalties},",
            name = py_string(&quantity.name),
            penalties = render_python_penalties(penalties)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("OBSERVATION_SPECS = {".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!(
            "    {name}: {{\"loss\": {loss}, \"schedule\": {schedule}}},",
            name = py_string(&name),
            loss = py_string(match observation.loss {
                crate::compile::LossKind::Mse => "mse",
                crate::compile::LossKind::Huber => "huber",
            }),
            schedule = py_string(match &observation.schedule {
                crate::compile::ObservationSchedule::DensePerStep => "dense_per_step",
                crate::compile::ObservationSchedule::Sparse(_) => "sparse",
            })
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("SLOT_INTERFACES = {".to_string());
    for slot in &bound.slot_bindings {
        let input_names = slot
            .inputs
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        let output_names = slot
            .provides
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        lines.push(format!(
            "    {:?}: {{\"kind\": {:?}, \"inputs\": {}, \"outputs\": {}, \"input_arity\": {}, \"output_arity\": {}}},",
            slot.slot,
            slot.kind_name(),
            render_py_string_list(&input_names),
            render_py_string_list(&output_names),
            slot.input_arity,
            slot.output_arity
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PLAN_METADATA = {".to_string());
    lines.push(format!(
        "    \"planned_slot_steps\": {},",
        plan.slot_steps.len()
    ));
    lines.push(format!(
        "    \"planned_equation_steps\": {},",
        plan.equation_steps.len()
    ));
    lines.push(format!(
        "    \"planned_temporal_steps\": {},",
        plan.temporal_steps.len()
    ));
    lines.push(format!(
        "    \"alternative_path_count\": {},",
        plan.alternatives.len()
    ));
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("def init_params():".to_string());
    if learned_initial_state_names.is_empty() {
        lines.push("    return {}".to_string());
    } else {
        lines.push("    return {".to_string());
        lines.push("        \"initial_state\": {".to_string());
        for name in &learned_initial_state_names {
            lines.push(format!("            {name}: 0.0,", name = py_string(name)));
        }
        lines.push("        },".to_string());
        lines.push("    }".to_string());
    }
    lines.push(String::new());

    lines.push("def _huber_loss(residual, delta=1.0):".to_string());
    lines.push("    abs_residual = abs(residual)".to_string());
    lines.push("    if abs_residual <= delta:".to_string());
    lines.push("        return 0.5 * residual * residual".to_string());
    lines.push("    return delta * (abs_residual - 0.5 * delta)".to_string());
    lines.push(String::new());

    lines.push("def _resolve_bound(bound, current):".to_string());
    lines.push("    if isinstance(bound, str):".to_string());
    lines.push("        return current[bound]".to_string());
    lines.push("    return bound".to_string());
    lines.push(String::new());

    lines.push("def _safe_div(numerator, denominator):".to_string());
    lines.push("    if abs(denominator) < SAFE_DIV_EPS:".to_string());
    lines.push(
        "        raise ZeroDivisionError(\"division denominator is too close to zero\")"
            .to_string(),
    );
    lines.push("    return numerator / denominator".to_string());
    lines.push(String::new());

    lines.push("def _bound_violation(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return 0.0".to_string());
    lines.push("    total = 0.0".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        total += max(lower_v - value, 0.0)".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        total += max(value - upper_v, 0.0)".to_string());
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def _require_keys(mapping, required, label):".to_string());
    lines.push("    mapping = {} if mapping is None else mapping".to_string());
    lines.push("    for name in required:".to_string());
    lines.push("        if name not in mapping:".to_string());
    lines.push("            raise KeyError(f\"missing {label} value for {name!r}\")".to_string());
    lines.push("    return mapping".to_string());
    lines.push(String::new());

    lines.push("def _assert_valid(name, value, current, label):".to_string());
    lines.push("    violation = _bound_violation(name, value, current)".to_string());
    lines.push("    if violation > 0.0:".to_string());
    lines.push(
        "        raise ValueError(f\"{label} for {name!r} violates declared bounds\")".to_string(),
    );
    lines.push(String::new());

    lines.push("def _project_output(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return value".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        value = max(value, _resolve_bound(lower, current))".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        value = min(value, _resolve_bound(upper, current))".to_string());
    lines.push("    return value".to_string());
    lines.push(String::new());

    lines.push(
        "def resolve_initial_state(initial_state=None, constants=None, params=None):".to_string(),
    );
    lines.push("    state = {} if initial_state is None else dict(initial_state)".to_string());
    lines.push("    constants = {} if constants is None else constants".to_string());
    lines.push(
        "    learned = {} if params is None else params.get(\"initial_state\", {})".to_string(),
    );
    lines.push("    current = {**constants, **state}".to_string());
    lines.push("    for name in LEARNED_INITIAL_STATE_NAMES:".to_string());
    lines.push("        if name not in learned:".to_string());
    lines.push(
        "            raise KeyError(f\"missing learned initial state parameter for {name!r}\")"
            .to_string(),
    );
    lines.push("        current[name] = learned[name]".to_string());
    lines.push("        state[name] = _project_output(name, current[name], current)".to_string());
    lines.push("        current[name] = state[name]".to_string());
    lines.push("    return state".to_string());
    lines.push(String::new());

    lines.push(
        "def validate_rollout_inputs(initial_state, forcing_steps, constants, slot_providers, params=None):"
            .to_string(),
    );
    lines
        .push("    constants = _require_keys(constants, CONSTANT_NAMES, \"constant\")".to_string());
    lines.push("    for name in CONSTANT_NAMES:".to_string());
    lines.push("        _assert_valid(name, constants[name], constants, \"constant\")".to_string());
    lines.push("    slot_providers = {} if slot_providers is None else slot_providers".to_string());
    lines.push("    for slot_name in LEARNED_SLOT_NAMES:".to_string());
    lines.push("        if slot_name not in slot_providers:".to_string());
    lines.push(
        "            raise KeyError(f\"missing learned slot provider for {slot_name!r}\")"
            .to_string(),
    );
    lines.push("    if forcing_steps is None:".to_string());
    lines.push("        raise KeyError(\"missing forcing steps\")".to_string());
    lines.push("    if len(forcing_steps) != HORIZON_STEPS:".to_string());
    lines.push(
        "        raise ValueError(f\"forcing step count {len(forcing_steps)} does not match compile horizon {HORIZON_STEPS}\")"
            .to_string(),
    );
    lines.push("    for step_index, forcing in enumerate(forcing_steps):".to_string());
    lines.push(
        "        _require_keys(forcing, FORCING_NAMES, f\"forcing step {step_index}\")".to_string(),
    );
    lines.push("        forcing_current = {**constants, **forcing}".to_string());
    lines.push("        for name in FORCING_NAMES:".to_string());
    lines.push(
        "            _assert_valid(name, forcing[name], forcing_current, f\"forcing step {step_index}\")"
            .to_string(),
    );
    lines.push("    initial_state = {} if initial_state is None else initial_state".to_string());
    lines.push(
        "    _require_keys(initial_state, REQUIRED_INITIAL_STATE_NAMES, \"initial state\")"
            .to_string(),
    );
    lines.push("    initial_current = {**constants, **initial_state}".to_string());
    lines.push("    for name in REQUIRED_INITIAL_STATE_NAMES:".to_string());
    lines.push(
        "        _assert_valid(name, initial_state[name], initial_current, \"initial state\")"
            .to_string(),
    );
    lines.push("    resolve_initial_state(initial_state, constants, params=params)".to_string());
    lines.push(String::new());

    if mode_emits_loss_helpers(bound.mode) {
        lines.push("def validate_observations(observations):".to_string());
        lines.push("    observations = {} if observations is None else observations".to_string());
        lines.push(
            "    _require_keys(observations, OBSERVATION_SPECS.keys(), \"observation payload\")"
                .to_string(),
        );
        lines.push("    for name in OBSERVATION_SPECS:".to_string());
        lines.push("        payload = observations[name]".to_string());
        lines.push(
            "        _require_keys(payload, [\"values\", \"mask\"], f\"observation {name}\")"
                .to_string(),
        );
        lines.push("        if len(payload[\"values\"]) != HORIZON_STEPS:".to_string());
        lines.push(
            "            raise ValueError(f\"observation {name!r} values length does not match compile horizon {HORIZON_STEPS}\")"
                .to_string(),
        );
        lines.push("        if len(payload[\"mask\"]) != HORIZON_STEPS:".to_string());
        lines.push(
            "            raise ValueError(f\"observation {name!r} mask length does not match compile horizon {HORIZON_STEPS}\")"
                .to_string(),
        );
        lines.push(String::new());
    }

    lines.push("def step(state, forcing, constants, slot_providers, dt):".to_string());
    lines.push("    current = {}".to_string());
    lines.push("    current[\"_alternatives\"] = {}".to_string());
    lines.push("    current[\"_constraint_violation\"] = 0.0".to_string());
    lines.push("    current.update(constants)".to_string());
    lines.push("    current.update(forcing)".to_string());
    lines.push("    current.update(state)".to_string());
    lines.push(String::new());

    for slot in &plan.slot_steps {
        emit_slot_step(experiment, slot, &mut lines);
    }
    for equation in &plan.equation_steps {
        emit_equation_step(
            experiment,
            equation,
            &mut lines,
            "current",
            Some("current"),
            Some("current[\"_constraint_violation\"]"),
            Some("mechanistic current output"),
        );
    }
    for alternative in consistency_alternatives(experiment) {
        emit_alternative_step(experiment, alternative, &mut lines);
    }

    lines.push("    next_state = dict(state)".to_string());
    for equation in &plan.temporal_steps {
        emit_equation_step(
            experiment,
            equation,
            &mut lines,
            "next_state",
            Some("{**current, **next_state}"),
            Some("current[\"_constraint_violation\"]"),
            Some("temporal state output"),
        );
    }
    lines.push("    return next_state, current".to_string());
    lines.push(String::new());

    lines.push(
        "def rollout(initial_state, forcing_steps, constants, slot_providers, dt, params=None):"
            .to_string(),
    );
    lines.push(
        "    validate_rollout_inputs(initial_state, forcing_steps, constants, slot_providers, params=params)"
            .to_string(),
    );
    lines.push(
        "    state = resolve_initial_state(initial_state, constants, params=params)".to_string(),
    );
    lines.push("    trajectory = []".to_string());
    lines.push("    for forcing in forcing_steps:".to_string());
    lines.push(
        "        state, current = step(state, forcing, constants, slot_providers, dt)".to_string(),
    );
    lines.push(
        "        trajectory.append({\"current\": dict(current), \"state\": dict(state)})"
            .to_string(),
    );
    lines.push("    return trajectory".to_string());
    lines.push(String::new());

    if mode_emits_loss_helpers(bound.mode) {
        lines.push("def obs_loss(trajectory, observations):".to_string());
        lines.push("    validate_observations(observations)".to_string());
        lines.push("    total = 0.0".to_string());
        for observation in &bound.observations {
            let name = quantity_name(experiment, observation.quantity);
            lines.push(format!("    _obs = observations.get({})", py_string(&name)));
            lines.push("    if _obs is None:".to_string());
            lines.push("        raise KeyError('missing observation payload')".to_string());
            lines.push("    _values = _obs[\"values\"]".to_string());
            lines.push("    _mask = _obs[\"mask\"]".to_string());
            lines.push("    observed_total = 0.0".to_string());
            lines.push("    observed_count = 0".to_string());
            lines.push("    for step_index, frame in enumerate(trajectory):".to_string());
            lines.push("        if not _mask[step_index]:".to_string());
            lines.push("            continue".to_string());
            lines.push(format!(
                "        residual = frame[\"current\"][{name}] - _values[step_index]",
                name = py_string(&name)
            ));
            match observation.loss {
                crate::compile::LossKind::Mse => {
                    lines.push("        observed_total += residual * residual".to_string());
                }
                crate::compile::LossKind::Huber => {
                    lines.push("        observed_total += _huber_loss(residual)".to_string());
                }
            }
            lines.push("        observed_count += 1".to_string());
            lines.push("    total += observed_total / max(observed_count, 1)".to_string());
        }
        lines.push("    return total".to_string());
        lines.push(String::new());

        let python_consistency_alternatives = consistency_alternatives(experiment);
        lines.push(
            "def consistency_loss(trajectory, forcing_steps=None, constants=None, slot_providers=None):"
                .to_string(),
        );
        if python_consistency_alternatives.is_empty() {
            lines.push("    return 0.0".to_string());
            lines.push(String::new());
        } else {
            lines.push("    total = 0.0".to_string());
            lines.push("    for frame in trajectory:".to_string());
            lines.push(
                "        alternatives = frame[\"current\"].get(\"_alternatives\", {})".to_string(),
            );
            lines.push("        for output_name, entries in alternatives.items():".to_string());
            lines.push("            canonical = frame[\"current\"][output_name]".to_string());
            lines.push("            for entry in entries:".to_string());
            lines.push("                residual = canonical - entry[\"value\"]".to_string());
            lines.push("                total += residual * residual".to_string());
            lines.push("    return total".to_string());
            lines.push(String::new());
        }

        lines.push("def constraint_violation_loss(trajectory):".to_string());
        lines.push(
            "    return sum(frame[\"current\"].get(\"_constraint_violation\", 0.0) for frame in trajectory)"
                .to_string(),
        );
        lines.push(String::new());

        lines.push("def soft_penalty_loss(trajectory):".to_string());
        lines.push("    total = 0.0".to_string());
        lines.push("    for name, penalties in PENALTY_METADATA.items():".to_string());
        lines.push("        for penalty in penalties:".to_string());
        lines.push("            if penalty[\"kind\"] == \"smooth\":".to_string());
        lines.push(
            "                values = [frame[\"current\"][name] for frame in trajectory]"
                .to_string(),
        );
        lines.push("                for prev, curr in zip(values, values[1:]):".to_string());
        lines.push("                    delta = curr - prev".to_string());
        lines.push("                    total += penalty[\"weight\"] * delta * delta".to_string());
        lines.push("    return total".to_string());
        lines.push(String::new());

        lines.push("def loss_components(trajectory, observations):".to_string());
        lines.push("    obs = obs_loss(trajectory, observations)".to_string());
        lines.push("    consistency = consistency_loss(trajectory)".to_string());
        lines.push("    constraint_violation = constraint_violation_loss(trajectory)".to_string());
        lines.push("    soft_penalty = soft_penalty_loss(trajectory)".to_string());
        lines.push("    return {".to_string());
        lines.push("        \"obs_loss\": obs,".to_string());
        lines.push("        \"consistency_loss\": consistency,".to_string());
        lines.push("        \"constraint_violation_loss\": constraint_violation,".to_string());
        lines.push("        \"soft_penalty_loss\": soft_penalty,".to_string());
        lines.push(
            "        \"total_loss\": obs + consistency + constraint_violation + soft_penalty,"
                .to_string(),
        );
        lines.push("    }".to_string());
        lines.push(String::new());

        lines.push("def total_loss(trajectory, observations):".to_string());
        lines.push(
            "    return loss_components(trajectory, observations)[\"total_loss\"]".to_string(),
        );
        lines.push(String::new());
    }

    lines.join("\n")
}

pub fn emit_jax_module(experiment: &PreparedExperiment) -> String {
    let model = &experiment.model;
    let bound = &experiment.bound;
    let plan = &experiment.plan;

    let mut lines = Vec::new();
    lines.push("# Generated by myco-core".to_string());
    lines.push("import jax.numpy as jnp".to_string());
    lines.push("import jax.nn as jnn".to_string());
    lines.push("from jax import lax".to_string());
    lines.push(String::new());
    lines.push(format!("MODEL_NAME = {:?}", model.syntax.name));
    lines.push(format!(
        "COMPILE_MODE = {:?}",
        compile_mode_name(bound.mode)
    ));
    lines.push(String::new());

    let quantity_names = model
        .equality
        .quantities
        .iter()
        .map(|quantity| quantity.name.as_str())
        .collect::<Vec<_>>();
    lines.push(format!(
        "QUANTITY_NAMES = {}",
        render_py_string_list(&quantity_names)
    ));

    let persistent_quantity_names = persistent_quantity_names(bound, experiment);
    lines.push(format!(
        "PERSISTENT_QUANTITY_NAMES = {}",
        render_py_string_list(&persistent_quantity_names)
    ));

    let forcing_names = forcing_quantity_names(experiment);
    lines.push(format!(
        "FORCING_NAMES = {}",
        render_py_string_list(&forcing_names)
    ));
    let constant_names = constant_quantity_names(experiment);
    lines.push(format!(
        "CONSTANT_NAMES = {}",
        render_py_string_list(&constant_names)
    ));
    lines.push(format!("HORIZON_STEPS = {}", bound.horizon_steps));
    lines.push("SAFE_DIV_EPS = 1e-8".to_string());
    let learned_initial_state_names = learned_initial_state_names(bound, experiment);
    let required_initial_state_names = required_initial_state_names(bound, experiment);
    let learned_slot_names = learned_slot_names(bound);
    lines.push(format!(
        "LEARNED_INITIAL_STATE_NAMES = {}",
        render_py_string_list(&learned_initial_state_names)
    ));
    lines.push(format!(
        "REQUIRED_INITIAL_STATE_NAMES = {}",
        render_py_string_list(&required_initial_state_names)
    ));
    lines.push(format!(
        "LEARNED_SLOT_NAMES = {}",
        render_py_string_list(&learned_slot_names)
    ));
    lines.push(format!(
        "CONSISTENCY_POLICY = {:?}",
        consistency_policy_name(bound.consistency_policy)
    ));
    lines.push(format!(
        "CONSTRAINT_RUNTIME_POLICY = {:?}",
        jax_constraint_runtime_policy_name()
    ));
    lines.push(format!(
        "LOSS_HELPERS_ENABLED = {}",
        if mode_emits_loss_helpers(bound.mode) {
            "True"
        } else {
            "False"
        }
    ));
    lines.push(String::new());

    lines.push("PROJECTION_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        if let Some(projection) = projection_metadata(experiment, quantity.id) {
            lines.push(format!(
                "    {name}: {projection},",
                name = py_string(&quantity.name)
            ));
        }
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push(format!(
        "TRAINABLE_METADATA = {{\"learned_initial_state\": {}, \"learned_slots\": {}}}",
        render_py_string_list(&learned_initial_state_names),
        render_py_string_list(&learned_slot_names)
    ));
    lines.push(String::new());

    lines.push("PENALTY_METADATA = {".to_string());
    for quantity in &model.equality.quantities {
        let penalties = &quantity.constraint_set.penalties;
        if penalties.is_empty() {
            continue;
        }
        lines.push(format!(
            "    {name}: {penalties},",
            name = py_string(&quantity.name),
            penalties = render_python_penalties(penalties)
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("OBSERVATION_SPECS = {".to_string());
    for observation in &bound.observations {
        let name = quantity_name(experiment, observation.quantity);
        lines.push(format!(
            "    {name}: {{\"loss\": {loss}, \"schedule\": {schedule}}},",
            name = py_string(&name),
            loss = py_string(match observation.loss {
                crate::compile::LossKind::Mse => "mse",
                crate::compile::LossKind::Huber => "huber",
            }),
            schedule = py_string(match &observation.schedule {
                crate::compile::ObservationSchedule::DensePerStep => "dense_per_step",
                crate::compile::ObservationSchedule::Sparse(_) => "sparse",
            })
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("SLOT_INTERFACES = {".to_string());
    for slot in &bound.slot_bindings {
        let input_names = slot
            .inputs
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        let output_names = slot
            .provides
            .iter()
            .map(|quantity| quantity_name(experiment, *quantity))
            .collect::<Vec<_>>();
        lines.push(format!(
            "    {:?}: {{\"kind\": {:?}, \"inputs\": {}, \"outputs\": {}, \"input_arity\": {}, \"output_arity\": {}}},",
            slot.slot,
            slot.kind_name(),
            render_py_string_list(&input_names),
            render_py_string_list(&output_names),
            slot.input_arity,
            slot.output_arity
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("PLAN_METADATA = {".to_string());
    lines.push(format!(
        "    \"planned_slot_steps\": {},",
        plan.slot_steps.len()
    ));
    lines.push(format!(
        "    \"planned_equation_steps\": {},",
        plan.equation_steps.len()
    ));
    lines.push(format!(
        "    \"planned_temporal_steps\": {},",
        plan.temporal_steps.len()
    ));
    lines.push(format!(
        "    \"alternative_path_count\": {},",
        plan.alternatives.len()
    ));
    lines.push("}".to_string());
    lines.push(String::new());

    lines.push("def init_params():".to_string());
    if learned_initial_state_names.is_empty() {
        lines.push("    return {}".to_string());
    } else {
        lines.push("    return {".to_string());
        lines.push("        \"initial_state\": {".to_string());
        for name in &learned_initial_state_names {
            lines.push(format!(
                "            {name}: jnp.asarray(0.0),",
                name = py_string(name)
            ));
        }
        lines.push("        },".to_string());
        lines.push("    }".to_string());
    }
    lines.push(String::new());

    lines.push("def _resolve_bound(bound, current):".to_string());
    lines.push("    if isinstance(bound, str):".to_string());
    lines.push("        return current[bound]".to_string());
    lines.push("    return jnp.asarray(bound)".to_string());
    lines.push(String::new());

    lines.push("def _safe_div(numerator, denominator):".to_string());
    lines.push("    denominator = jnp.asarray(denominator)".to_string());
    lines.push("    eps = jnp.asarray(SAFE_DIV_EPS, dtype=denominator.dtype)".to_string());
    lines.push("    safe_denominator = jnp.where(".to_string());
    lines.push("        jnp.abs(denominator) < eps,".to_string());
    lines.push("        jnp.where(denominator >= 0, eps, -eps),".to_string());
    lines.push("        denominator,".to_string());
    lines.push("    )".to_string());
    lines.push("    return numerator / safe_denominator".to_string());
    lines.push(String::new());

    lines.push("def _bound_violation(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return jnp.asarray(0.0)".to_string());
    lines.push("    value = jnp.asarray(value)".to_string());
    lines.push("    total = jnp.asarray(0.0)".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        total = total + jnp.sum(jnp.maximum(lower_v - value, 0.0))".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        total = total + jnp.sum(jnp.maximum(value - upper_v, 0.0))".to_string());
    lines.push("    return total".to_string());
    lines.push(String::new());

    lines.push("def _require_keys(mapping, required, label):".to_string());
    lines.push("    mapping = {} if mapping is None else mapping".to_string());
    lines.push("    for name in required:".to_string());
    lines.push("        if name not in mapping:".to_string());
    lines.push("            raise KeyError(f\"missing {label} value for {name!r}\")".to_string());
    lines.push("    return mapping".to_string());
    lines.push(String::new());

    lines.push("def _assert_valid(name, value, current, label):".to_string());
    lines.push("    violation = _bound_violation(name, value, current)".to_string());
    lines.push("    if bool(violation > 0):".to_string());
    lines.push(
        "        raise ValueError(f\"{label} for {name!r} violates declared bounds\")".to_string(),
    );
    lines.push(String::new());

    lines.push("def _project_output(name, value, current):".to_string());
    lines.push("    spec = PROJECTION_METADATA.get(name)".to_string());
    lines.push("    if spec is None:".to_string());
    lines.push("        return value".to_string());
    lines.push("    lower = spec.get(\"lower\")".to_string());
    lines.push("    upper = spec.get(\"upper\")".to_string());
    lines.push("    if lower is not None and upper is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        span = upper_v - lower_v".to_string());
    lines.push("        return lower_v + span * jnn.sigmoid(value)".to_string());
    lines.push("    if lower is not None:".to_string());
    lines.push("        lower_v = _resolve_bound(lower, current)".to_string());
    lines.push("        return lower_v + jnn.softplus(value - lower_v)".to_string());
    lines.push("    if upper is not None:".to_string());
    lines.push("        upper_v = _resolve_bound(upper, current)".to_string());
    lines.push("        return upper_v - jnn.softplus(upper_v - value)".to_string());
    lines.push("    return value".to_string());
    lines.push(String::new());

    lines.push(
        "def resolve_initial_state(initial_state=None, constants=None, params=None):".to_string(),
    );
    lines.push("    state = {} if initial_state is None else dict(initial_state)".to_string());
    lines.push("    constants = {} if constants is None else constants".to_string());
    lines.push(
        "    learned = {} if params is None else params.get(\"initial_state\", {})".to_string(),
    );
    lines.push("    current = {**constants, **state}".to_string());
    lines.push("    for name in LEARNED_INITIAL_STATE_NAMES:".to_string());
    lines.push("        if name not in learned:".to_string());
    lines.push(
        "            raise KeyError(f\"missing learned initial state parameter for {name!r}\")"
            .to_string(),
    );
    lines.push("        current[name] = jnp.asarray(learned[name])".to_string());
    lines.push("        state[name] = _project_output(name, current[name], current)".to_string());
    lines.push("        current[name] = state[name]".to_string());
    lines.push("    return state".to_string());
    lines.push(String::new());

    lines.push(
        "def validate_rollout_inputs(initial_state, forcing_series, constants, slot_providers, params=None):"
            .to_string(),
    );
    lines
        .push("    constants = _require_keys(constants, CONSTANT_NAMES, \"constant\")".to_string());
    lines.push("    for name in CONSTANT_NAMES:".to_string());
    lines.push("        _assert_valid(name, constants[name], constants, \"constant\")".to_string());
    lines.push(
        "    forcing_series = _require_keys(forcing_series, FORCING_NAMES, \"forcing\")"
            .to_string(),
    );
    lines.push("    slot_providers = {} if slot_providers is None else slot_providers".to_string());
    lines.push("    for slot_name in LEARNED_SLOT_NAMES:".to_string());
    lines.push("        if slot_name not in slot_providers:".to_string());
    lines.push(
        "            raise KeyError(f\"missing learned slot provider for {slot_name!r}\")"
            .to_string(),
    );
    lines.push("    for name in FORCING_NAMES:".to_string());
    lines.push("        if forcing_series[name].shape[0] != HORIZON_STEPS:".to_string());
    lines.push(
        "            raise ValueError(f\"forcing series for {name!r} does not match compile horizon {HORIZON_STEPS}\")"
            .to_string(),
    );
    lines.push("        _assert_valid(name, forcing_series[name], {**constants, **forcing_series}, \"forcing series\")".to_string());
    lines.push("    initial_state = {} if initial_state is None else initial_state".to_string());
    lines.push(
        "    _require_keys(initial_state, REQUIRED_INITIAL_STATE_NAMES, \"initial state\")"
            .to_string(),
    );
    lines.push("    initial_current = {**constants, **initial_state}".to_string());
    lines.push("    for name in REQUIRED_INITIAL_STATE_NAMES:".to_string());
    lines.push(
        "        _assert_valid(name, initial_state[name], initial_current, \"initial state\")"
            .to_string(),
    );
    lines.push("    resolve_initial_state(initial_state, constants, params=params)".to_string());
    lines.push(String::new());

    if mode_emits_loss_helpers(bound.mode) {
        lines.push("def validate_observations(observations):".to_string());
        lines.push("    observations = {} if observations is None else observations".to_string());
        lines.push(
            "    _require_keys(observations, OBSERVATION_SPECS.keys(), \"observation payload\")"
                .to_string(),
        );
        lines.push("    for name in OBSERVATION_SPECS:".to_string());
        lines.push("        payload = observations[name]".to_string());
        lines.push(
            "        _require_keys(payload, [\"values\", \"mask\"], f\"observation {name}\")"
                .to_string(),
        );
        lines.push("        if payload[\"values\"].shape[0] != HORIZON_STEPS:".to_string());
        lines.push(
            "            raise ValueError(f\"observation {name!r} values length does not match compile horizon {HORIZON_STEPS}\")"
                .to_string(),
        );
        lines.push("        if payload[\"mask\"].shape[0] != HORIZON_STEPS:".to_string());
        lines.push(
            "            raise ValueError(f\"observation {name!r} mask length does not match compile horizon {HORIZON_STEPS}\")"
                .to_string(),
        );
        lines.push(String::new());
    }

    lines.push("def _huber_loss(residual, delta=1.0):".to_string());
    lines.push("    abs_residual = jnp.abs(residual)".to_string());
    lines.push("    return jnp.where(abs_residual <= delta, 0.5 * residual * residual, delta * (abs_residual - 0.5 * delta))".to_string());
    lines.push(String::new());

    lines.push("def step(state, forcing, constants, slot_providers, dt):".to_string());
    lines.push("    current = {**constants, **forcing, **state}".to_string());
    lines.push("    constraint_violation = jnp.asarray(0.0)".to_string());
    for slot in &plan.slot_steps {
        emit_slot_step(experiment, slot, &mut lines);
    }
    for equation in &plan.equation_steps {
        emit_equation_step(
            experiment,
            equation,
            &mut lines,
            "current",
            Some("current"),
            Some("constraint_violation"),
            None,
        );
    }
    lines.push("    next_state = dict(state)".to_string());
    for equation in &plan.temporal_steps {
        emit_equation_step(
            experiment,
            equation,
            &mut lines,
            "next_state",
            Some("{**current, **next_state}"),
            Some("constraint_violation"),
            None,
        );
    }
    lines.push("    current[\"_constraint_violation\"] = constraint_violation".to_string());
    lines.push("    return next_state, current".to_string());
    lines.push(String::new());

    lines.push(
        "def rollout(initial_state, forcing_series, constants, slot_providers, dt, params=None):"
            .to_string(),
    );
    lines.push(
        "    validate_rollout_inputs(initial_state, forcing_series, constants, slot_providers, params=params)"
            .to_string(),
    );
    lines.push("    def _scan_step(state, forcing_t):".to_string());
    lines.push(
        "        next_state, current = step(state, forcing_t, constants, slot_providers, dt)"
            .to_string(),
    );
    lines.push("        return next_state, current".to_string());
    lines.push(
        "    initial_state = resolve_initial_state(initial_state, constants, params=params)"
            .to_string(),
    );
    lines.push("    return lax.scan(_scan_step, initial_state, forcing_series)".to_string());
    lines.push(String::new());

    if mode_emits_loss_helpers(bound.mode) {
        lines.push("def obs_loss(history, observations):".to_string());
        lines.push("    validate_observations(observations)".to_string());
        lines.push("    total = 0.0".to_string());
        for observation in &bound.observations {
            let name = quantity_name(experiment, observation.quantity);
            lines.push(format!("    _obs = observations.get({})", py_string(&name)));
            lines.push("    if _obs is None:".to_string());
            lines.push("        raise KeyError('missing observation payload')".to_string());
            lines.push("    _values = jnp.asarray(_obs[\"values\"])".to_string());
            lines.push("    _mask = jnp.asarray(_obs[\"mask\"])".to_string());
            lines.push(format!(
                "    _residual = history[{name}] - _values",
                name = py_string(&name)
            ));
            lines.push("    _count = jnp.maximum(jnp.sum(_mask), 1)".to_string());
            match observation.loss {
                crate::compile::LossKind::Mse => {
                    lines.push(
                        "    total += jnp.sum(jnp.where(_mask, _residual * _residual, 0.0)) / _count"
                            .to_string(),
                    );
                }
                crate::compile::LossKind::Huber => {
                    lines.push(
                        "    total += jnp.sum(jnp.where(_mask, _huber_loss(_residual), 0.0)) / _count"
                            .to_string(),
                    );
                }
            }
        }
        lines.push("    return total".to_string());
        lines.push(String::new());

        let jax_consistency_alternatives = consistency_alternatives(experiment);
        lines.push(
            "def consistency_loss(history, forcing_series=None, constants=None, slot_providers=None):"
                .to_string(),
        );
        if jax_consistency_alternatives.is_empty() {
            lines.push("    return jnp.asarray(0.0)".to_string());
            lines.push(String::new());
        } else {
            lines.push(
                "    forcing_series = {} if forcing_series is None else forcing_series".to_string(),
            );
            lines.push("    constants = {} if constants is None else constants".to_string());
            lines.push(
                "    slot_providers = {} if slot_providers is None else slot_providers".to_string(),
            );
            lines.push("    total = jnp.asarray(0.0)".to_string());
            for alternative in &jax_consistency_alternatives {
                if let AlternativePayload::Equation { expression } = &alternative.payload {
                    let output_name = quantity_name(experiment, alternative.output);
                    let alt_expr = render_history_expr_for_output_unit(
                        experiment,
                        alternative.output,
                        expression,
                    );
                    lines.push(format!(
                        "    _residual = history[{output}] - ({alt_expr})",
                        output = py_string(&output_name)
                    ));
                    lines.push("    total += jnp.sum(_residual * _residual)".to_string());
                } else if let AlternativePayload::Slot {
                    kind,
                    inputs,
                    output_index,
                } = &alternative.payload
                {
                    let output_name = quantity_name(experiment, alternative.output);
                    let alt_expr = render_slot_output_expr_for_history(
                        experiment,
                        &alternative.source,
                        *kind,
                        inputs,
                        alternative.output,
                        *output_index,
                    );
                    lines.push(format!(
                        "    _residual = history[{output}] - ({alt_expr})",
                        output = py_string(&output_name)
                    ));
                    lines.push("    total += jnp.sum(_residual * _residual)".to_string());
                }
            }
            lines.push("    return total".to_string());
            lines.push(String::new());
        }

        lines.push("def constraint_violation_loss(history):".to_string());
        lines.push("    return jnp.sum(history[\"_constraint_violation\"])".to_string());
        lines.push(String::new());

        lines.push("def soft_penalty_loss(history):".to_string());
        lines.push("    total = 0.0".to_string());
        lines.push("    for name, penalties in PENALTY_METADATA.items():".to_string());
        lines.push("        values = history[name]".to_string());
        lines.push("        for penalty in penalties:".to_string());
        lines.push("            if penalty[\"kind\"] == \"smooth\":".to_string());
        lines.push("                delta = values[1:] - values[:-1]".to_string());
        lines.push(
            "                total += penalty[\"weight\"] * jnp.sum(delta * delta)".to_string(),
        );
        lines.push("    return total".to_string());
        lines.push(String::new());

        lines.push(
            "def loss_components(history, observations, forcing_series=None, constants=None, slot_providers=None):"
                .to_string(),
        );
        lines.push("    constants = {} if constants is None else constants".to_string());
        lines.push(
            "    slot_providers = {} if slot_providers is None else slot_providers".to_string(),
        );
        lines.push("    obs = obs_loss(history, observations)".to_string());
        lines.push(
            "    consistency = consistency_loss(history, forcing_series=forcing_series, constants=constants, slot_providers=slot_providers)"
                .to_string(),
        );
        lines.push("    constraint_violation = constraint_violation_loss(history)".to_string());
        lines.push("    soft_penalty = soft_penalty_loss(history)".to_string());
        lines.push("    return {".to_string());
        lines.push("        \"obs_loss\": obs,".to_string());
        lines.push("        \"consistency_loss\": consistency,".to_string());
        lines.push("        \"constraint_violation_loss\": constraint_violation,".to_string());
        lines.push("        \"soft_penalty_loss\": soft_penalty,".to_string());
        lines.push(
            "        \"total_loss\": obs + consistency + constraint_violation + soft_penalty,"
                .to_string(),
        );
        lines.push("    }".to_string());
        lines.push(String::new());

        lines.push(
            "def total_loss(history, observations, forcing_series=None, constants=None, slot_providers=None):"
                .to_string(),
        );
        lines.push("    return loss_components(history, observations, forcing_series=forcing_series, constants=constants, slot_providers=slot_providers)[\"total_loss\"]".to_string());
        lines.push(String::new());
    }

    lines.join("\n")
}

fn emit_slot_step(experiment: &PreparedExperiment, slot: &PlannedSlot, lines: &mut Vec<String>) {
    if slot.kind == SlotBindingKind::Learned && slot.outputs.len() > 1 {
        let call = render_learned_slot_call(experiment, &slot.slot, &slot.inputs, "current");
        lines.push(format!("    _slot_out = {call}"));
        for (index, output) in slot.outputs.iter().enumerate() {
            lines.push(format!(
                "    current[{output}] = _project_output({output}, _slot_out[{index}], current)",
                output = py_string(&quantity_name(experiment, *output))
            ));
        }
        return;
    }

    for (index, output) in slot.outputs.iter().enumerate() {
        let raw_value = render_slot_output_expr_for_step(
            experiment,
            &slot.slot,
            slot.kind,
            &slot.inputs,
            *output,
            index,
        );
        let output_name = quantity_name(experiment, *output);
        lines.push(format!(
            "    current[{output}] = _project_output({output}, {raw_value}, current)",
            output = py_string(&output_name)
        ));
    }
}

fn emit_equation_step(
    experiment: &PreparedExperiment,
    equation: &PlannedEquation,
    lines: &mut Vec<String>,
    target_map: &str,
    validation_context: Option<&str>,
    violation_sink: Option<&str>,
    raise_label: Option<&str>,
) {
    let target = quantity_name(experiment, equation.output);
    let expr = render_expr_for_output_unit(experiment, equation.output, &equation.expression);
    lines.push(format!(
        "    {target_map}[{target}] = {expr}",
        target = py_string(&target)
    ));
    if let Some(context) = validation_context {
        lines.push(format!(
            "    {sink} += _bound_violation({target}, {target_map}[{target}], {context})",
            sink = violation_sink.expect("validation requires a violation sink"),
            target = py_string(&target)
        ));
        if let Some(label) = raise_label {
            lines.push(format!(
                "    _assert_valid({target}, {target_map}[{target}], {context}, {label})",
                target = py_string(&target),
                label = py_string(label)
            ));
        }
    }
}

fn emit_alternative_step(
    experiment: &PreparedExperiment,
    alternative: &crate::plan::AlternativePath,
    lines: &mut Vec<String>,
) {
    let output_name = quantity_name(experiment, alternative.output);
    let value_expr = match &alternative.payload {
        AlternativePayload::Equation { expression } => {
            render_expr_for_output_unit(experiment, alternative.output, expression)
        }
        AlternativePayload::Slot {
            kind,
            inputs,
            output_index,
        } => render_slot_output_expr_for_current(
            experiment,
            &alternative.source,
            *kind,
            inputs,
            alternative.output,
            *output_index,
        ),
    };

    lines.push(format!(
        "    current[\"_alternatives\"].setdefault({output}, []).append({{\"source\": {source}, \"direction\": {direction}, \"value\": {value}}})",
        output = py_string(&output_name),
        source = py_string(&alternative_source_label(&alternative.source)),
        direction = py_string(match alternative.direction {
            crate::plan::CandidateDirection::Forward => "forward",
            crate::plan::CandidateDirection::Inverted => "inverted",
            crate::plan::CandidateDirection::Provider => "provider",
        }),
        value = value_expr
    ));
}

fn render_expr_base(experiment: &PreparedExperiment, expr: &CoreExpr) -> String {
    match expr {
        CoreExpr::Quantity(reference) => match reference.time {
            TimeReference::Implicit | TimeReference::Relative(0) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "current[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            TimeReference::Relative(1) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "next_state[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            other => panic!("unsupported time reference in emitter: {other:?}"),
        },
        CoreExpr::Special(SpecialRef::Dt) => "dt".to_string(),
        CoreExpr::Number(number) => number.clone(),
        CoreExpr::Binary { op, left, right } => {
            let left = render_expr_base(experiment, left);
            let right = render_expr_base(experiment, right);
            match op {
                crate::semantic::BinaryOp::Add => format!("({left} + {right})"),
                crate::semantic::BinaryOp::Sub => format!("({left} - {right})"),
                crate::semantic::BinaryOp::Mul => format!("({left} * {right})"),
                crate::semantic::BinaryOp::Div => format!("_safe_div({left}, {right})"),
            }
        }
    }
}

fn render_expr_for_output_unit(
    experiment: &PreparedExperiment,
    output: QuantityId,
    expr: &CoreExpr,
) -> String {
    let expr_base = render_expr_base(experiment, expr);
    scale_from_base(experiment, output, expr_base)
}

fn render_history_expr_base(experiment: &PreparedExperiment, expr: &CoreExpr) -> String {
    match expr {
        CoreExpr::Quantity(reference) => match reference.time {
            TimeReference::Implicit | TimeReference::Relative(0) => format!(
                "{}",
                render_quantity_read(
                    experiment,
                    reference.quantity,
                    &format!(
                        "history[{name}]",
                        name = py_string(&quantity_name(experiment, reference.quantity))
                    )
                )
            ),
            TimeReference::Relative(1) => {
                panic!("next-step references are not supported in JAX history expressions")
            }
            other => panic!("unsupported time reference in JAX history emitter: {other:?}"),
        },
        CoreExpr::Special(SpecialRef::Dt) => "1.0".to_string(),
        CoreExpr::Number(number) => number.clone(),
        CoreExpr::Binary { op, left, right } => {
            let left = render_history_expr_base(experiment, left);
            let right = render_history_expr_base(experiment, right);
            match op {
                crate::semantic::BinaryOp::Add => format!("({left} + {right})"),
                crate::semantic::BinaryOp::Sub => format!("({left} - {right})"),
                crate::semantic::BinaryOp::Mul => format!("({left} * {right})"),
                crate::semantic::BinaryOp::Div => format!("_safe_div({left}, {right})"),
            }
        }
    }
}

fn render_history_expr_for_output_unit(
    experiment: &PreparedExperiment,
    output: QuantityId,
    expr: &CoreExpr,
) -> String {
    let expr_base = render_history_expr_base(experiment, expr);
    scale_from_base(experiment, output, expr_base)
}

fn quantity_name(experiment: &PreparedExperiment, quantity: QuantityId) -> String {
    experiment.model.equality.quantities[quantity.0]
        .name
        .clone()
}

fn scale_to_base(experiment: &PreparedExperiment, quantity: QuantityId) -> i64 {
    experiment.model.equality.quantities[quantity.0]
        .type_info
        .scale_to_base
}

fn render_quantity_read(
    experiment: &PreparedExperiment,
    quantity: QuantityId,
    expression: &str,
) -> String {
    let scale = scale_to_base(experiment, quantity);
    if scale == 1 {
        expression.to_string()
    } else {
        format!("({expression} * {})", render_scale(scale))
    }
}

fn scale_from_base(
    experiment: &PreparedExperiment,
    quantity: QuantityId,
    expression: String,
) -> String {
    let scale = scale_to_base(experiment, quantity);
    if scale == 1 {
        expression
    } else {
        format!("(({expression}) / {})", render_scale(scale))
    }
}

fn render_scale(scale: i64) -> String {
    format!("{scale:?}")
}

fn render_py_string_list(values: &[impl AsRef<str>]) -> String {
    let items = values
        .iter()
        .map(|value| py_string(value.as_ref()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{items}]")
}

fn py_string(value: &str) -> String {
    format!("{value:?}")
}

fn alternative_source_label(source: &crate::plan::PlanSource) -> String {
    match source {
        crate::plan::PlanSource::Slot(name) => name.clone(),
        crate::plan::PlanSource::Equation { block_name, .. } => block_name.clone(),
    }
}

fn forcing_quantity_names(experiment: &PreparedExperiment) -> Vec<String> {
    let mut names = experiment
        .bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::DataSeries { .. }) => Some(quantity.quantity.name.clone()),
            _ => None,
        })
        .collect::<Vec<_>>();
    for slot in &experiment.bound.slot_bindings {
        if slot.kind == SlotBindingKind::DataSeries {
            names.extend(
                slot.provides
                    .iter()
                    .map(|quantity| quantity_name(experiment, *quantity)),
            );
        }
    }
    names.sort();
    names.dedup();
    names
}

fn constant_quantity_names(experiment: &PreparedExperiment) -> Vec<String> {
    let mut names = experiment
        .bound
        .quantities
        .iter()
        .filter_map(|quantity| match &quantity.direct_binding {
            Some(DirectBindingKind::Constant) => Some(quantity.quantity.name.clone()),
            _ => None,
        })
        .collect::<Vec<_>>();
    for slot in &experiment.bound.slot_bindings {
        if slot.kind == SlotBindingKind::Constant {
            names.extend(
                slot.provides
                    .iter()
                    .map(|quantity| quantity_name(experiment, *quantity)),
            );
        }
    }
    names.sort();
    names.dedup();
    names
}

fn learned_initial_state_names(
    bound: &crate::compile::BoundModel,
    experiment: &PreparedExperiment,
) -> Vec<String> {
    let mut names = bound
        .direct_bindings
        .iter()
        .filter_map(|binding| match binding.kind {
            DirectBindingKind::InitialState {
                source: InitialStateSource::Learned,
            } => Some(quantity_name(experiment, binding.quantity)),
            _ => None,
        })
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    names
}

fn persistent_quantity_names(
    bound: &crate::compile::BoundModel,
    experiment: &PreparedExperiment,
) -> Vec<String> {
    let mut names = bound
        .quantities
        .iter()
        .filter(|quantity| quantity.persistent)
        .map(|quantity| quantity_name(experiment, quantity.quantity.id))
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    names
}

fn required_initial_state_names(
    bound: &crate::compile::BoundModel,
    experiment: &PreparedExperiment,
) -> Vec<String> {
    let mut names = bound
        .direct_bindings
        .iter()
        .filter_map(|binding| match binding.kind {
            DirectBindingKind::InitialState {
                source: InitialStateSource::Learned,
            } => None,
            DirectBindingKind::InitialState { .. } => {
                Some(quantity_name(experiment, binding.quantity))
            }
            _ => None,
        })
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    names
}

fn learned_slot_names(bound: &crate::compile::BoundModel) -> Vec<String> {
    let mut names = bound
        .slot_bindings
        .iter()
        .filter(|slot| slot.kind == SlotBindingKind::Learned)
        .map(|slot| slot.slot.clone())
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    names
}

fn consistency_policy_name(policy: ConsistencyPolicy) -> &'static str {
    match policy {
        ConsistencyPolicy::Off => "off",
        ConsistencyPolicy::EquationOnly => "equation_only",
        ConsistencyPolicy::All => "all",
    }
}

fn python_constraint_runtime_policy_name() -> &'static str {
    "project_learned_raise_derived"
}

fn jax_constraint_runtime_policy_name() -> &'static str {
    "project_learned_penalize_derived"
}

fn mode_emits_loss_helpers(mode: crate::compile::CompileMode) -> bool {
    !matches!(mode, crate::compile::CompileMode::Simulate)
}

fn consistency_alternatives<'a>(
    experiment: &'a PreparedExperiment,
) -> Vec<&'a crate::plan::AlternativePath> {
    experiment
        .plan
        .alternatives
        .iter()
        .filter(|alternative| match experiment.bound.consistency_policy {
            ConsistencyPolicy::Off => false,
            ConsistencyPolicy::EquationOnly => {
                matches!(alternative.payload, AlternativePayload::Equation { .. })
            }
            ConsistencyPolicy::All => true,
        })
        .collect()
}

fn slot_name_from_source(source: &crate::plan::PlanSource) -> &str {
    match source {
        crate::plan::PlanSource::Slot(slot) => slot,
        crate::plan::PlanSource::Equation { .. } => {
            unreachable!("slot payload requires slot source")
        }
    }
}

fn render_learned_slot_call(
    experiment: &PreparedExperiment,
    slot_name: &str,
    inputs: &[QuantityId],
    quantity_map: &str,
) -> String {
    format!(
        "slot_providers[{name}]({args})",
        name = py_string(slot_name),
        args = inputs
            .iter()
            .map(|quantity| format!(
                "{quantity_map}[{name}]",
                name = py_string(&quantity_name(experiment, *quantity))
            ))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn render_slot_output_expr_for_step(
    experiment: &PreparedExperiment,
    slot_name: &str,
    kind: SlotBindingKind,
    inputs: &[QuantityId],
    output: QuantityId,
    output_index: usize,
) -> String {
    let output_name = py_string(&quantity_name(experiment, output));
    match kind {
        SlotBindingKind::DataSeries => format!("forcing[{output_name}]"),
        SlotBindingKind::Constant => format!("constants[{output_name}]"),
        SlotBindingKind::Learned => {
            let call = render_learned_slot_call(experiment, slot_name, inputs, "current");
            if output_index == 0 {
                call
            } else {
                format!("({call})[{output_index}]")
            }
        }
    }
}

fn render_slot_output_expr_for_current(
    experiment: &PreparedExperiment,
    source: &crate::plan::PlanSource,
    kind: SlotBindingKind,
    inputs: &[QuantityId],
    output: QuantityId,
    output_index: usize,
) -> String {
    let raw = match kind {
        SlotBindingKind::DataSeries => {
            format!("forcing[{}]", py_string(&quantity_name(experiment, output)))
        }
        SlotBindingKind::Constant => {
            format!(
                "constants[{}]",
                py_string(&quantity_name(experiment, output))
            )
        }
        SlotBindingKind::Learned => {
            let call = render_learned_slot_call(
                experiment,
                slot_name_from_source(source),
                inputs,
                "current",
            );
            if output_index == 0 {
                call
            } else {
                format!("({call})[{output_index}]")
            }
        }
    };
    format!(
        "_project_output({output}, {raw}, current)",
        output = py_string(&quantity_name(experiment, output))
    )
}

fn render_slot_output_expr_for_history(
    experiment: &PreparedExperiment,
    source: &crate::plan::PlanSource,
    kind: SlotBindingKind,
    inputs: &[QuantityId],
    output: QuantityId,
    output_index: usize,
) -> String {
    let output_name = py_string(&quantity_name(experiment, output));
    let raw = match kind {
        SlotBindingKind::DataSeries => format!("forcing_series[{output_name}]"),
        SlotBindingKind::Constant => format!("constants[{output_name}]"),
        SlotBindingKind::Learned => {
            let call = render_learned_slot_call(
                experiment,
                slot_name_from_source(source),
                inputs,
                "history",
            );
            if output_index == 0 {
                call
            } else {
                format!("({call})[{output_index}]")
            }
        }
    };
    format!("_project_output({output_name}, {raw}, history)")
}

fn compile_mode_name(mode: crate::compile::CompileMode) -> &'static str {
    match mode {
        crate::compile::CompileMode::Simulate => "simulate",
        crate::compile::CompileMode::Fit => "fit",
        crate::compile::CompileMode::Train => "train",
    }
}

fn projection_metadata(experiment: &PreparedExperiment, quantity: QuantityId) -> Option<String> {
    let constraint_set = &experiment.model.equality.quantities[quantity.0].constraint_set;
    let lower = constraint_set.lower.clone();
    let upper = constraint_set.upper.clone();

    if lower.is_none() && upper.is_none() {
        return None;
    }

    let mut fields = Vec::new();
    if let Some(bound) = lower {
        fields.push(format!("\"lower\": {}", render_projection_bound(&bound)));
    }
    if let Some(bound) = upper {
        fields.push(format!("\"upper\": {}", render_projection_bound(&bound)));
    }

    Some(format!("{{{}}}", fields.join(", ")))
}

fn render_projection_bound(bound: &ConstraintBound) -> String {
    match bound {
        ConstraintBound::Number(value) => value.clone(),
        ConstraintBound::Quantity(name) => py_string(name),
    }
}

fn render_python_penalties(penalties: &[PenaltySpec]) -> String {
    let rendered = penalties
        .iter()
        .map(|penalty| match penalty {
            PenaltySpec::Smooth { weight } => {
                format!("{{\"kind\": \"smooth\", \"weight\": {weight}}}")
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{rendered}]")
}

trait SlotKindName {
    fn kind_name(&self) -> &'static str;
}

impl SlotKindName for crate::compile::ResolvedSlotBinding {
    fn kind_name(&self) -> &'static str {
        match self.kind {
            crate::compile::SlotBindingKind::DataSeries => "data_series",
            crate::compile::SlotBindingKind::Constant => "constant",
            crate::compile::SlotBindingKind::Learned => "learned",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        compile::{
            CompileMode, CompileSpec, ConsistencyPolicy, DirectBindingKind, DirectBindingSpec,
            InitialStateSource, LossKind, ObservationSchedule, ObservationSpec, SlotBindingKind,
            SlotBindingSpec,
        },
        pipeline::{load_model, prepare_experiment},
    };

    const TINY_TREE: &str = include_str!("../tests/fixtures/tiny_tree.myco");

    #[test]
    fn emits_python_module_for_tiny_tree() {
        let model = load_model(TINY_TREE).expect("model should load");
        let experiment =
            prepare_experiment(&model, &tiny_tree_spec()).expect("experiment should prepare");
        let module = emit_python_module(&experiment);

        assert!(module.contains("MODEL_NAME = \"TinyTree\""));
        assert!(module.contains("COMPILE_MODE = \"train\""));
        assert!(module.contains("LOSS_HELPERS_ENABLED = True"));
        assert!(module.contains("CONSTRAINT_RUNTIME_POLICY = \"project_learned_raise_derived\""));
        assert!(module.contains("HORIZON_STEPS = 24"));
        assert!(module.contains("SAFE_DIV_EPS = 1e-8"));
        assert!(module.contains("PERSISTENT_QUANTITY_NAMES = [\"carbon\", \"water\"]"));
        assert!(module.contains("REQUIRED_INITIAL_STATE_NAMES = [\"carbon\", \"water\"]"));
        assert!(module.contains("LEARNED_SLOT_NAMES = [\"controller\"]"));
        assert!(module.contains("TRAINABLE_METADATA = {\"learned_initial_state\": [], \"learned_slots\": [\"controller\"]}"));
        assert!(module.contains("PROJECTION_METADATA = {"));
        assert!(module.contains("\"stomata\": {\"lower\": 0, \"upper\": \"g_max\"},"));
        assert!(module.contains("OBSERVATION_SPECS = {"));
        assert!(module.contains(
            "def validate_rollout_inputs(initial_state, forcing_steps, constants, slot_providers, params=None):"
        ));
        assert!(module.contains("def validate_observations(observations):"));
        assert!(module.contains("def _safe_div(numerator, denominator):"));
        assert!(module.contains("def _assert_valid(name, value, current, label):"));
        assert!(module.contains("def constraint_violation_loss(trajectory):"));
        assert!(module.contains("def step(state, forcing, constants, slot_providers, dt):"));
        assert!(module.contains(
            "def rollout(initial_state, forcing_steps, constants, slot_providers, dt, params=None):"
        ));
        assert!(module.contains(
            "validate_rollout_inputs(initial_state, forcing_steps, constants, slot_providers, params=params)"
        ));
        assert!(module.contains("def obs_loss(trajectory, observations):"));
        assert!(module.contains("validate_observations(observations)"));
        assert!(module.contains("observed_total / max(observed_count, 1)"));
        assert!(module.contains(
            "def consistency_loss(trajectory, forcing_steps=None, constants=None, slot_providers=None):"
        ));
        assert!(module.contains("def total_loss(trajectory, observations):"));
        assert!(module.contains("\"constraint_violation_loss\": constraint_violation,"));
        assert!(module.contains(
            "current[\"stomata\"] = _project_output(\"stomata\", slot_providers[\"controller\"]("
        ));
        assert!(
            module.contains("current[\"_alternatives\"].setdefault(\"transpiration\", []).append(")
        );
        assert!(module.contains(
            "current[\"transpiration\"] = (current[\"stomata\"] * current[\"vpd_scale\"])"
        ));
        assert!(module.contains(
            "next_state[\"water\"] = (current[\"water\"] - (dt * current[\"transpiration\"]))"
        ));
    }

    #[test]
    fn emits_jax_module_for_tiny_tree() {
        let model = load_model(TINY_TREE).expect("model should load");
        let experiment =
            prepare_experiment(&model, &tiny_tree_spec()).expect("experiment should prepare");
        let module = emit_jax_module(&experiment);

        assert!(module.contains("import jax.numpy as jnp"));
        assert!(module.contains("import jax.nn as jnn"));
        assert!(module.contains("from jax import lax"));
        assert!(module.contains("COMPILE_MODE = \"train\""));
        assert!(module.contains("LOSS_HELPERS_ENABLED = True"));
        assert!(
            module.contains("CONSTRAINT_RUNTIME_POLICY = \"project_learned_penalize_derived\"")
        );
        assert!(module.contains("HORIZON_STEPS = 24"));
        assert!(module.contains("SAFE_DIV_EPS = 1e-8"));
        assert!(module.contains("PERSISTENT_QUANTITY_NAMES = [\"carbon\", \"water\"]"));
        assert!(module.contains("REQUIRED_INITIAL_STATE_NAMES = [\"carbon\", \"water\"]"));
        assert!(module.contains("LEARNED_SLOT_NAMES = [\"controller\"]"));
        assert!(module.contains("TRAINABLE_METADATA = {\"learned_initial_state\": [], \"learned_slots\": [\"controller\"]}"));
        assert!(module.contains(
            "def validate_rollout_inputs(initial_state, forcing_series, constants, slot_providers, params=None):"
        ));
        assert!(module.contains("def validate_observations(observations):"));
        assert!(module.contains("def _safe_div(numerator, denominator):"));
        assert!(module.contains("def _assert_valid(name, value, current, label):"));
        assert!(module.contains("def constraint_violation_loss(history):"));
        assert!(module.contains("return lax.scan(_scan_step, initial_state, forcing_series)"));
        assert!(module.contains(
            "validate_rollout_inputs(initial_state, forcing_series, constants, slot_providers, params=params)"
        ));
        assert!(module.contains("jnp.where"));
        assert!(module.contains("jnp.maximum(jnp.sum(_mask), 1)"));
        assert!(module.contains("jnn.sigmoid"));
        assert!(module.contains("jnn.softplus"));
        assert!(module.contains("current[\"_constraint_violation\"] = constraint_violation"));
        assert!(module.contains(
            "def consistency_loss(history, forcing_series=None, constants=None, slot_providers=None):"
        ));
        assert!(module.contains("history[\"transpiration\"] - ((history[\"hydraulic_cond\"] * (history[\"soil_water\"] - history[\"water\"])))"));
    }

    #[test]
    fn emits_soft_penalty_metadata_and_loss_code() {
        let source = r#"
model Penalized

external forcing : scalar
state water : scalar
node stomata : scalar {
  self >= 0
  self <= g_max
  penalty smooth(weight=0.25)
}
node g_max : scalar

slot controller provides [stomata]:
  inputs = [forcing, g_max]

temporal water_step:
  water[t+1] = water[t] + stomata[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Train,
                horizon_steps: 8,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "forcing".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..8).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "g_max".to_string(),
                        kind: DirectBindingKind::Constant,
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![SlotBindingSpec {
                    slot: "controller".to_string(),
                    kind: SlotBindingKind::Learned,
                }],
                observations: vec![ObservationSpec {
                    quantity: "stomata".to_string(),
                    loss: LossKind::Mse,
                    schedule: ObservationSchedule::DensePerStep,
                }],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("PENALTY_METADATA = {"));
        assert!(python_module.contains("\"stomata\": [{\"kind\": \"smooth\", \"weight\": 0.25}],"));
        assert!(python_module.contains("def soft_penalty_loss(trajectory):"));
        assert!(python_module.contains("total += penalty[\"weight\"] * delta * delta"));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("PENALTY_METADATA = {"));
        assert!(jax_module.contains("\"stomata\": [{\"kind\": \"smooth\", \"weight\": 0.25}],"));
        assert!(jax_module.contains("def soft_penalty_loss(history):"));
        assert!(jax_module.contains("delta = values[1:] - values[:-1]"));
        assert!(jax_module.contains("total += penalty[\"weight\"] * jnp.sum(delta * delta)"));
    }

    #[test]
    fn emits_jax_inverted_equation_when_plan_uses_recovery_path() {
        let source = r#"
model Recover

external vpd_scale : scalar
state water : scalar
node stomata : scalar
node transpiration : scalar

relation demand_transpiration:
  transpiration = stomata * vpd_scale

temporal water_step:
  water[t+1] = water[t] - transpiration[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 12,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "vpd_scale".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "transpiration".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let module = emit_jax_module(&experiment);
        assert!(module.contains(
            "current[\"stomata\"] = _safe_div(current[\"transpiration\"], current[\"vpd_scale\"])"
        ));
    }

    #[test]
    fn emits_unit_conversion_for_equation_outputs() {
        let source = r#"
model UnitConvert

node x : potential@MPa
node y : potential@kPa

relation assign:
  x = y
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 1,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![DirectBindingSpec {
                    quantity: "y".to_string(),
                    kind: DirectBindingKind::Constant,
                }],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("current[\"x\"] = "));
        assert!(python_module.contains("current[\"y\"] * 1000"));
        assert!(python_module.contains("/ 1000000"));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("current[\"x\"] = "));
        assert!(jax_module.contains("current[\"y\"] * 1000"));
        assert!(jax_module.contains("/ 1000000"));
    }

    #[test]
    fn emits_learned_initial_state_parameters() {
        let source = r#"
model LearnedInit

state water : scalar {
  self >= 0
}

temporal water_step:
  water[t+1] = water[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 4,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![DirectBindingSpec {
                    quantity: "water".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Learned,
                    },
                }],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("LEARNED_INITIAL_STATE_NAMES = [\"water\"]"));
        assert!(python_module.contains("\"initial_state\": {"));
        assert!(python_module.contains("\"water\": 0.0"));
        assert!(python_module.contains(
            "def resolve_initial_state(initial_state=None, constants=None, params=None):"
        ));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("LEARNED_INITIAL_STATE_NAMES = [\"water\"]"));
        assert!(jax_module.contains("\"water\": jnp.asarray(0.0)"));
        assert!(jax_module.contains(
            "initial_state = resolve_initial_state(initial_state, constants, params=params)"
        ));
    }

    #[test]
    fn emits_data_and_constant_slot_runtime_semantics() {
        let source = r#"
model SlotKinds

external forcing : scalar
state water : scalar
node data_out : scalar
node const_out : scalar

slot data_slot provides [data_out]:
  inputs = [forcing]

slot const_slot provides [const_out]:
  inputs = [forcing]

temporal water_step:
  water[t+1] = water[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 4,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![DirectBindingSpec {
                    quantity: "water".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                }],
                slot_bindings: vec![
                    SlotBindingSpec {
                        slot: "data_slot".to_string(),
                        kind: SlotBindingKind::DataSeries,
                    },
                    SlotBindingSpec {
                        slot: "const_slot".to_string(),
                        kind: SlotBindingKind::Constant,
                    },
                ],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("FORCING_NAMES = [\"data_out\"]"));
        assert!(python_module.contains("CONSTANT_NAMES = [\"const_out\"]"));
        assert!(python_module.contains(
            "current[\"data_out\"] = _project_output(\"data_out\", forcing[\"data_out\"], current)"
        ));
        assert!(python_module.contains(
            "current[\"const_out\"] = _project_output(\"const_out\", constants[\"const_out\"], current)"
        ));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("FORCING_NAMES = [\"data_out\"]"));
        assert!(jax_module.contains("CONSTANT_NAMES = [\"const_out\"]"));
        assert!(jax_module.contains(
            "current[\"data_out\"] = _project_output(\"data_out\", forcing[\"data_out\"], current)"
        ));
        assert!(jax_module.contains(
            "current[\"const_out\"] = _project_output(\"const_out\", constants[\"const_out\"], current)"
        ));
    }

    #[test]
    fn consistency_policy_off_disables_emission() {
        let model = load_model(TINY_TREE).expect("model should load");
        let mut spec = tiny_tree_spec();
        spec.consistency_policy = ConsistencyPolicy::Off;
        let experiment = prepare_experiment(&model, &spec).expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("CONSISTENCY_POLICY = \"off\""));
        assert!(python_module.contains("def consistency_loss(trajectory, forcing_steps=None, constants=None, slot_providers=None):"));
        assert!(python_module.contains("    return 0.0"));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("CONSISTENCY_POLICY = \"off\""));
        assert!(jax_module.contains("def consistency_loss(history, forcing_series=None, constants=None, slot_providers=None):"));
        assert!(jax_module.contains("    return jnp.asarray(0.0)"));
    }

    #[test]
    fn simulate_mode_omits_loss_helpers() {
        let model = load_model(TINY_TREE).expect("model should load");
        let mut spec = tiny_tree_spec();
        spec.mode = CompileMode::Simulate;
        spec.observations.clear();
        let experiment = prepare_experiment(&model, &spec).expect("experiment should prepare");

        let python_module = emit_python_module(&experiment);
        assert!(python_module.contains("COMPILE_MODE = \"simulate\""));
        assert!(python_module.contains("LOSS_HELPERS_ENABLED = False"));
        assert!(!python_module.contains("def obs_loss("));
        assert!(!python_module.contains("def total_loss("));

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("COMPILE_MODE = \"simulate\""));
        assert!(jax_module.contains("LOSS_HELPERS_ENABLED = False"));
        assert!(!jax_module.contains("def obs_loss("));
        assert!(!jax_module.contains("def total_loss("));
    }

    #[test]
    fn consistency_policy_all_emits_slot_alternatives_in_jax() {
        let source = r#"
model SlotAlternative

external forcing : scalar
state water : scalar
node x : scalar
node y : scalar

slot provider provides [x]:
  inputs = [forcing]

relation y_rule:
  y = forcing

relation x_rule:
  x = y + forcing

temporal water_step:
  water[t+1] = water[t] + x[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Train,
                horizon_steps: 4,
                consistency_policy: ConsistencyPolicy::All,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "forcing".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..4).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![SlotBindingSpec {
                    slot: "provider".to_string(),
                    kind: SlotBindingKind::Learned,
                }],
                observations: vec![ObservationSpec {
                    quantity: "x".to_string(),
                    loss: LossKind::Mse,
                    schedule: ObservationSchedule::DensePerStep,
                }],
            },
        )
        .expect("experiment should prepare");

        let jax_module = emit_jax_module(&experiment);
        assert!(jax_module.contains("CONSISTENCY_POLICY = \"all\""));
        assert!(jax_module.contains("slot_providers[\"provider\"]("));
        assert!(jax_module.contains("history[\"forcing\"]"));
    }

    #[test]
    fn emits_inverted_equation_when_plan_uses_recovery_path() {
        let source = r#"
model Recover

external vpd_scale : scalar
state water : scalar
node stomata : scalar
node transpiration : scalar

relation demand_transpiration:
  transpiration = stomata * vpd_scale

temporal water_step:
  water[t+1] = water[t] - transpiration[t]
"#;

        let model = load_model(source).expect("model should load");
        let experiment = prepare_experiment(
            &model,
            &CompileSpec {
                mode: CompileMode::Simulate,
                horizon_steps: 12,
                consistency_policy: ConsistencyPolicy::EquationOnly,
                direct_bindings: vec![
                    DirectBindingSpec {
                        quantity: "vpd_scale".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "transpiration".to_string(),
                        kind: DirectBindingKind::DataSeries {
                            steps: (0..12).collect(),
                        },
                    },
                    DirectBindingSpec {
                        quantity: "water".to_string(),
                        kind: DirectBindingKind::InitialState {
                            source: InitialStateSource::Constant,
                        },
                    },
                ],
                slot_bindings: vec![],
                observations: vec![],
            },
        )
        .expect("experiment should prepare");

        let module = emit_python_module(&experiment);
        assert!(module.contains(
            "current[\"stomata\"] = _safe_div(current[\"transpiration\"], current[\"vpd_scale\"])"
        ));
    }

    fn tiny_tree_spec() -> CompileSpec {
        CompileSpec {
            mode: CompileMode::Train,
            horizon_steps: 24,
            consistency_policy: ConsistencyPolicy::EquationOnly,
            direct_bindings: vec![
                DirectBindingSpec {
                    quantity: "vpd_scale".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "soil_water".to_string(),
                    kind: DirectBindingKind::DataSeries {
                        steps: (0..24).collect(),
                    },
                },
                DirectBindingSpec {
                    quantity: "hydraulic_cond".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "g_max".to_string(),
                    kind: DirectBindingKind::Constant,
                },
                DirectBindingSpec {
                    quantity: "water".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
                DirectBindingSpec {
                    quantity: "carbon".to_string(),
                    kind: DirectBindingKind::InitialState {
                        source: InitialStateSource::Constant,
                    },
                },
            ],
            slot_bindings: vec![SlotBindingSpec {
                slot: "controller".to_string(),
                kind: SlotBindingKind::Learned,
            }],
            observations: vec![ObservationSpec {
                quantity: "transpiration".to_string(),
                loss: LossKind::Mse,
                schedule: ObservationSchedule::DensePerStep,
            }],
        }
    }
}
